import type {Metadata} from "next";
import {SiteFooter,SiteHeader} from "@/app/components/site-chrome";
import "../legal-pages.css";

export const metadata:Metadata={title:"Allgemeine Geschäftsbedingungen",description:"AGB für Nutzer von Rechtsfall-Check.de.",alternates:{canonical:"/agb"}};
const Toc=()=> <nav className="legal-toc" aria-label="Inhalt"><strong>INHALT</strong>{[["geltung","Geltung"],["leistung","Leistung"],["vertrag","Vertragsschluss"],["konto","Nutzerkonto"],["pflichten","Nutzerpflichten"],["zahlung","Preis & Zahlung"],["bereitstellung","Bereitstellung"],["widerruf","Widerruf"],["rechte","Nutzungsrechte"],["haftung","Haftung"],["beendigung","Beendigung"],["schluss","Schlussbestimmungen"]].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav>;

export default function TermsPage(){return <div className="site"><SiteHeader/><main>
  <header className="legal-hero"><span className="section-label">VERTRAGSBEDINGUNGEN</span><h1>Allgemeine Geschäftsbedingungen</h1><p>Für die Nutzung von Rechtsfall-Check.de und die entgeltliche Beauftragung eines Rechtsfall Checks.</p></header>
  <div className="legal-shell"><Toc/><article className="legal-content"><span className="legal-version">Stand: 27. Juli 2026</span>
    <p>Diese AGB regeln das Vertragsverhältnis zwischen der Media Online Innovations Group, Inhaber Martin Kelm, Im Weidenblech 25, 51371 Leverkusen („Anbieter“), und den Nutzern von Rechtsfall-Check.de.</p>
    <section id="geltung"><h2>1. Geltungsbereich und Vertragspartner</h2><p>Die AGB gelten für Verbraucher im Sinne des § 13 BGB und – soweit ausdrücklich vereinbart – Unternehmer im Sinne des § 14 BGB. Abweichende Bedingungen des Nutzers werden nur Vertragsbestandteil, wenn der Anbieter ihrer Geltung ausdrücklich zustimmt.</p><p>Vertragspartner ist die Media Online Innovations Group, Inhaber Martin Kelm. Vertragssprache ist Deutsch.</p></section>
    <section id="leistung"><h2>2. Gegenstand und Grenzen der Leistung</h2><p>Der Rechtsfall Check ist eine digitale, KI-gestützte Vorprüfung. Der Nutzer erfasst einen Sachverhalt, kann Unterlagen hochladen und erhält – abhängig von Vollständigkeit, technischer Verarbeitbarkeit und Qualitätsgates – eine strukturierte, nicht abschließende Ersteinschätzung.</p><p>Die Leistung kann insbesondere eine Sachverhaltsstruktur, erkannte und fehlende Tatsachen, mögliche rechtliche Anknüpfungspunkte, offene Fragen, Unsicherheiten und Hinweise auf weiteren Prüfbedarf umfassen.</p><div className="legal-note"><strong>Keine anwaltliche Rechtsberatung:</strong> Der Anbieter ist keine Rechtsanwaltskanzlei. Die Ausgabe ersetzt keine individuelle anwaltliche Beratung, Vertretung, Fristenkontrolle oder verbindliche rechtliche Würdigung. Sie enthält keine Garantie für Richtigkeit, Vollständigkeit, Durchsetzbarkeit oder Erfolgsaussichten.</div><p>Bei akuten Fristen, gerichtlichen Zustellungen, Strafverfahren, drohender Haft, Durchsuchungen, Abschiebung, Gewalt- oder Notfallsituationen ist unverzüglich qualifizierte anwaltliche beziehungsweise behördliche Hilfe in Anspruch zu nehmen.</p></section>
    <section id="vertrag"><h2>3. Registrierung und Vertragsschluss</h2><p>Das Anlegen eines Kontos und einer Fallakte ist zunächst kostenlos. Ein entgeltlicher Vertrag über einen Rechtsfall Check kommt zustande, wenn der Nutzer im Bestellprozess die Leistungsbeschreibung, den Gesamtpreis und diese AGB erhält, die zahlungspflichtige Bestellung eindeutig auslöst und der Anbieter die Bestellung bestätigt beziehungsweise die Leistung freischaltet.</p><p>Die Darstellung auf der Website ist noch kein bindendes Angebot. Der Anbieter kann Bestellungen bei technischen, rechtlichen oder sicherheitsbezogenen Hinderungsgründen ablehnen. Eingabefehler können vor Absenden der Bestellung über die Formular- und Navigationsfunktionen berichtigt werden.</p></section>
    <section id="konto"><h2>4. Nutzerkonto und Zugangsdaten</h2><p>Nutzer müssen richtige und aktuelle Angaben machen, Zugangsdaten geheim halten und den Anbieter über erkennbaren Missbrauch informieren. Konten sind persönlich und dürfen nicht ohne Zustimmung übertragen werden. Der Anbieter darf Zugänge vorübergehend sperren, wenn konkrete Anhaltspunkte für Missbrauch, Angriffe, Rechtsverletzungen oder eine Gefährdung anderer Nutzer bestehen.</p></section>
    <section id="pflichten"><h2>5. Angaben, Unterlagen und Rechte Dritter</h2><p>Der Nutzer ist für die von ihm eingegebenen und hochgeladenen Inhalte verantwortlich. Er darf nur Inhalte übermitteln, die für den eigenen Fall erforderlich sind und an denen er die notwendigen Rechte besitzt oder deren Verarbeitung rechtlich zulässig ist.</p><ul><li>Unnötige Daten Dritter sollen geschwärzt oder weggelassen werden.</li><li>Keine rechtswidrig beschafften, manipulierten, schädlichen oder fremden Unterlagen ohne Rechtsgrundlage.</li><li>Keine Nutzung zur Begehung, Vorbereitung oder Verschleierung rechtswidriger Handlungen.</li><li>Keine automatisierten Massenabfragen, Sicherheitsangriffe oder Umgehung technischer Grenzen.</li></ul><p>Der Nutzer soll Tatsachen vollständig und wahrheitsgemäß schildern. Unvollständige, falsche oder missverständliche Angaben können zu einer Nicht-Antwort oder unzutreffenden Einordnung führen.</p></section>
    <section id="zahlung"><h2>6. Preis und Zahlung</h2><p>Ein Rechtsfall Check kostet 19,00 Euro je verbindlich eingereichtem Fall einschließlich der gesetzlich anfallenden Umsatzsteuer, soweit diese anfällt. Jeder weitere Rechtsfall Check wird gesondert beauftragt und berechnet. Es entsteht kein Abonnement und keine automatische Verlängerung. Der im Bestellschritt ausgewiesene Gesamtpreis ist maßgeblich.</p><p>Die Zahlung ist vor der verbindlichen Einreichung des Falls fällig. Die Zahlungsabwicklung erfolgt über Stripe. Verfügbare Zahlungsmittel werden im Checkout angezeigt. Upload und Analyse werden grundsätzlich erst nach dem serverseitig bestätigten Zahlungseingang für die betreffende Fallakte freigeschaltet.</p></section>
    <section id="bereitstellung"><h2>7. Bereitstellung und technische Voraussetzungen</h2><p>Die Leistung wird im Nutzerkonto bereitgestellt. Der Nutzer benötigt ein internetfähiges Gerät, einen aktuellen Browser und eine funktionierende E-Mail-Adresse. Ein konkreter Fertigstellungstermin wird im Bestellprozess angegeben; soweit nichts anderes vereinbart ist, beginnt die Verarbeitung nach Zahlung und Vorliegen der erforderlichen Angaben.</p><p>Wartung, Sicherheitsmaßnahmen, Störungen bei Drittanbietern oder höhere Gewalt können die Bereitstellung vorübergehend beeinträchtigen. Gesetzliche Ansprüche bei Nicht- oder Schlechtleistung bleiben unberührt.</p></section>
    <section id="widerruf"><h2>8. Widerrufsrecht für Verbraucher</h2><h3>Widerrufsbelehrung</h3><p>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsschlusses.</p><p>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns – Media Online Innovations Group, Inhaber Martin Kelm, Im Weidenblech 25, 51371 Leverkusen, Telefon 0214 / 330 140 60, E-Mail <a href="mailto:mail@media-online-innovations.group">mail@media-online-innovations.group</a> – mittels einer eindeutigen Erklärung über Ihren Entschluss informieren. Sie können das nachstehende Muster verwenden, das jedoch nicht vorgeschrieben ist.</p><p>Zur Wahrung der Frist reicht es aus, dass Sie die Mitteilung vor Ablauf der Widerrufsfrist absenden.</p><h3>Folgen des Widerrufs</h3><p>Wenn Sie den Vertrag widerrufen, erstatten wir alle von Ihnen erhaltenen Zahlungen unverzüglich und spätestens binnen vierzehn Tagen ab Eingang des Widerrufs. Für die Rückzahlung verwenden wir dasselbe Zahlungsmittel, sofern nichts anderes vereinbart wurde.</p><p>Haben Sie verlangt, dass die Dienstleistung während der Widerrufsfrist beginnt, kann für die bis zum Widerruf bereits erbrachte Leistung ein angemessener Betrag anfallen, soweit die gesetzlichen Voraussetzungen erfüllt sind. Bei digitalen Inhalten beziehungsweise vollständiger Dienstleistung kann das Widerrufsrecht unter den Voraussetzungen des § 356 BGB vorzeitig erlöschen. Hierüber werden Sie vor der zahlungspflichtigen Bestellung gesondert informiert; erforderliche Zustimmungen werden gesondert eingeholt.</p><div className="withdrawal-form"><h3>Muster-Widerrufsformular</h3><p>An: Media Online Innovations Group, Martin Kelm, Im Weidenblech 25, 51371 Leverkusen, mail@media-online-innovations.group</p><p>Hiermit widerrufe ich den von mir abgeschlossenen Vertrag über folgenden Rechtsfall Check:</p><p>Bestellt am: __________<br/>Name: __________<br/>Anschrift: __________<br/>E-Mail des Nutzerkontos: __________<br/>Datum: __________<br/>Unterschrift (nur bei Mitteilung auf Papier): __________</p></div></section>
    <section id="rechte"><h2>9. Nutzungsrechte</h2><p>Der Nutzer behält seine Rechte an eigenen Inhalten. Er räumt dem Anbieter die für Speicherung, technische Verarbeitung, Analyse und vertragsgemäße Bereitstellung erforderlichen, zeitlich auf die Vertragsdurchführung begrenzten Rechte ein. Eine Nutzung der Fallinhalte zu Werbezwecken oder zum Training allgemeiner KI-Modelle ist nicht Vertragszweck.</p><p>Der Nutzer darf sein Ergebnis für eigene Zwecke speichern und verwenden. Rechte an Software, Gestaltung, Marken, Datenbankstruktur und allgemeinen Produktinhalten verbleiben beim Anbieter beziehungsweise den jeweiligen Rechteinhabern.</p></section>
    <section id="haftung"><h2>10. Gewährleistung und Haftung</h2><p>Es gelten die gesetzlichen Mängelrechte. Der Anbieter haftet unbeschränkt bei Vorsatz, grober Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit sowie nach zwingenden gesetzlichen Vorschriften. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den vertragstypischen, vorhersehbaren Schaden begrenzt.</p><p>Keine Haftungsbeschränkung verändert zwingende Verbraucherrechte. Der Anbieter haftet nicht dafür, dass eine nicht anwaltliche Vorprüfung einen bestimmten rechtlichen oder wirtschaftlichen Erfolg erzielt. Der Nutzer bleibt verantwortlich, Fristen und verbindliche Entscheidungen durch hierzu befugte Stellen prüfen zu lassen.</p></section>
    <section id="beendigung"><h2>11. Vertragsdauer, Kontolöschung und Sperrung</h2><p>Der einzelne entgeltliche Vertrag endet mit vollständiger Bereitstellung, ohne dass dadurch gesetzliche Gewährleistungs-, Aufbewahrungs- oder Datenschutzpflichten entfallen. Das kostenlose Nutzerkonto kann im Bereich „Mein Konto“ mit einer Widerrufsfrist von 30 Tagen zur Löschung vorgemerkt werden. Bis zum angezeigten Löschtermin kann der Nutzer den Auftrag dort widerrufen. Alternativ kann er nach gesonderter Bestätigung die sofortige Kontolöschung wählen und damit auf die 30-tägige Widerrufsmöglichkeit verzichten.</p><p>Mit der endgültigen Löschung entfallen der Zugang sowie sämtliche in unserer aktiven Anwendungsumgebung gespeicherten Konto- und Fallinhalte unwiderruflich. Ausnahmen für eigenständige gesetzliche Aufzeichnungen von Zahlungs- und Infrastrukturbetreibern sowie Sicherungskopien richten sich nach der Datenschutzerklärung und den gesetzlichen Vorgaben.</p></section>
    <section id="schluss"><h2>12. Datenschutz, Streitbeilegung und Schlussbestimmungen</h2><p>Informationen zur Verarbeitung personenbezogener Daten enthält die <a href="/datenschutz">Datenschutzerklärung</a>. Der Anbieter ist nicht bereit und nicht verpflichtet, an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p><p>Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Bei Verbrauchern gilt diese Rechtswahl nur, soweit dadurch zwingender Schutz des Staates ihres gewöhnlichen Aufenthalts nicht entzogen wird. Für Gerichtsstände gelten die gesetzlichen Vorschriften.</p><p>Sollte eine Bestimmung unwirksam sein, bleiben die übrigen Bestimmungen wirksam. An die Stelle der unwirksamen Regelung treten die gesetzlichen Vorschriften.</p></section>
  </article></div><SiteFooter/></main></div>}
