"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { legalAreas } from "@/lib/legal-areas";

type Contact = {
  matchId: string; matchStatus: string; distanceKm: number | null; legalArea: string;
  caseId: string; caseTitle: string; firmName: string; city: string; biography: string | null;
  websiteUrl: string | null; publicEmail: string | null; publicPhone: string | null;
  lawyerName: string | null; areas: string[]; userConsentAt: string | null;
};
type Message = { id: string; senderRole: string; body: string; createdAt: string };

function MatchChat({ matchId, role }: { matchId: string; role: "MEMBER" | "LAWYER" }) {
  const [messages, setMessages] = useState<Message[]>([]); const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/v1/lawyer-matches/${matchId}/messages`, { cache: "no-store" }).then(r=>r.ok?r.json():null).then(d=>setMessages(d?.messages||[])); }, [matchId]);
  async function send(event: FormEvent) { event.preventDefault(); if (!message.trim()) return; setBusy(true); setError("");
    const response=await fetch(`/api/v1/lawyer-matches/${matchId}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message})});
    const data=await response.json().catch(()=>null); setBusy(false); if(!response.ok)return setError(data?.error?.message||"Nachricht konnte nicht gesendet werden.");
    setMessages(current=>[...current,data.message]); setMessage(""); }
  return <section className="match-chat"><h3>Geschützter Kontakt</h3><div className="match-chat-log" aria-live="polite">{messages.length?messages.map(item=><article className={item.senderRole===role?"own":""} key={item.id}><span>{item.senderRole===role?"Sie":item.senderRole==="LAWYER"?"Kanzlei":"Nutzer"}</span><p>{item.body}</p><small>{new Date(item.createdAt).toLocaleString("de-DE")}</small></article>):<p>Noch keine Nachrichten. Der Nutzer kann den Kontakt mit einer ersten Nachricht beginnen.</p>}</div>
    <form onSubmit={send}><label htmlFor={`message-${matchId}`}>Nachricht</label><textarea id={`message-${matchId}`} value={message} onChange={e=>setMessage(e.target.value)} maxLength={5000} rows={4} required/><button className="button" disabled={busy}>{busy?"Wird gesendet …":"Nachricht senden →"}</button>{error&&<span role="alert">{error}</span>}</form></section>;
}

export function LawyerContacts({ initialContacts, lawyerView, eligibleCases }: { initialContacts: Contact[]; lawyerView: boolean; eligibleCases: Array<{id:string;title:string}> }) {
  const [contacts,setContacts]=useState(initialContacts); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
  async function select(matchId:string){setBusy(matchId);setError("");const response=await fetch(`/api/v1/lawyer-matches/${matchId}/select`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({consent:true})});const data=await response.json().catch(()=>null);setBusy("");if(!response.ok)return setError(data?.error?.message||"Kontakt konnte nicht freigegeben werden.");setContacts(current=>current.map(item=>item.matchId===matchId?{...item,matchStatus:"CONTACT_RELEASED",userConsentAt:new Date().toISOString()}:item));}
  async function findMatches(caseId:string){setBusy(`locate-${caseId}`);setError("");if(!navigator.geolocation){setBusy("");return setError("Ihr Browser unterstützt keine Standortfreigabe.");}navigator.geolocation.getCurrentPosition(async position=>{const response=await fetch(`/api/v1/cases/${caseId}/lawyer-matches`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({latitude:position.coords.latitude,longitude:position.coords.longitude,locationConsent:true})});const data=await response.json().catch(()=>null);setBusy("");if(!response.ok)return setError(data?.error?.message||"Passende Profile konnten nicht ermittelt werden.");window.location.reload();},()=>{setBusy("");setError("Der Standort wurde nicht freigegeben. Ohne Standort ist keine verlässliche Radiusprüfung möglich.");},{enableHighAccuracy:false,timeout:10000,maximumAge:300000});}
  return <div className="profile-content"><header className="member-heading"><span>{lawyerView?"ANFRAGEN":"PASSENDE ANWALTSPROFILE"}</span><h1>{lawyerView?"Ihre freigegebenen Kontakte":"Sie entscheiden, wer zu Ihnen passt."}</h1><p>{lawyerView?"Hier erscheinen ausschließlich Nutzer, die Ihr Profil ausgewählt und ihre Daten freigegeben haben.":"Die Vorschläge beruhen auf Rechtsgebiet, Kanzleistandort, Tätigkeitsradius und aktueller Mandatsbereitschaft."}</p></header>
    {!contacts.length&&<section className="profile-section"><h2>{lawyerView?"Noch keine Kontaktanfrage":"Noch kein passender Vorschlag verfügbar"}</h2><p>{lawyerView?"Sie bleiben für Nutzer unsichtbar, bis Ihr Profil zu einem bezahlten Rechtsfall passt und ausgewählt wurde.":"Sobald geprüfte und aktive Profile die Matching-Kriterien erfüllen, werden sie hier angezeigt."}</p></section>}
    {!lawyerView&&eligibleCases.length>0&&<section className="profile-section location-match"><h2>Passende Kanzleien in Ihrer Nähe finden</h2><p>Für die einmalige Entfernungsberechnung verwendet Ihr Browser nach Ihrer Freigabe den ungefähren aktuellen Standort. Die Koordinaten werden nicht dauerhaft gespeichert und nicht an Kanzleien weitergegeben.</p><div>{eligibleCases.map(item=><button className="button" type="button" key={item.id} disabled={busy===`locate-${item.id}`} onClick={()=>findMatches(item.id)}>{busy===`locate-${item.id}`?"Standort wird geprüft …":`Anwälte für „${item.title}“ finden →`}</button>)}</div></section>}
    {error&&<div className="profile-notice error" role="alert">{error}</div>}
    <div className="contact-list">{contacts.map(contact=><article className="contact-card" key={contact.matchId}><header><div className="contact-avatar">§</div><div><small>{lawyerView?"FREIGEGEBENER KONTAKT":"GEPRÜFTES ANWALTSPROFIL"}</small><h2>{lawyerView?contact.caseTitle:contact.firmName}</h2><p>{lawyerView?`Rechtsgebiet: ${legalAreas.find(a=>a.id===contact.legalArea)?.title||contact.legalArea}`:`${contact.lawyerName||"Rechtsanwalt/Rechtsanwältin"} · ${contact.city}${contact.distanceKm!==null?` · ${contact.distanceKm} km entfernt`:""}`}</p></div></header>
      {!lawyerView&&<><p>{contact.biography||"Die Kanzlei hat noch keine zusätzliche Kurzbeschreibung hinterlegt."}</p><div className="contact-areas">{contact.areas.map(id=><span key={id}>{legalAreas.find(a=>a.id===id)?.title||id}</span>)}</div></>}
      {!lawyerView&&contact.matchStatus==="SUGGESTED"&&<div className="contact-consent"><p>Mit Ihrer Auswahl erlauben Sie die Übermittlung Ihrer Kontaktdaten und des vollständigen Prüfberichts an diese Kanzlei. Dadurch entsteht noch kein Mandat.</p><button className="button" type="button" disabled={busy===contact.matchId} onClick={()=>select(contact.matchId)}>{busy===contact.matchId?"Wird freigegeben …":"Kanzlei auswählen und Chat öffnen →"}</button></div>}
      {lawyerView&&<Link className="report-link" href={`/fallraum/${contact.caseId}/bericht?match=${encodeURIComponent(contact.matchId)}`} target="_blank">Freigegebenen Prüfbericht öffnen ↗</Link>}
      {contact.matchStatus!=="SUGGESTED"&&<MatchChat matchId={contact.matchId} role={lawyerView?"LAWYER":"MEMBER"}/>}</article>)}</div>
    <style jsx>{`.contact-list{display:grid;gap:18px}.contact-card{padding:26px;border:1px solid #d7e2e9;border-radius:18px;background:#fff}.contact-card>header{display:flex;gap:16px;align-items:center}.contact-avatar{width:56px;height:56px;display:grid;place-items:center;border-radius:15px;background:#0b3048;color:#fff;font-size:24px;font-weight:850}.contact-card small{font-size:9px;letter-spacing:.13em;color:#397dcc;font-weight:850}.contact-card h2{margin:5px 0;font-size:23px}.contact-card header p{margin:0;color:#687985}.contact-card>p{line-height:1.7;color:#405765}.contact-areas{display:flex;flex-wrap:wrap;gap:7px}.contact-areas span{padding:7px 10px;border-radius:99px;background:#deebfb;color:#164e79;font-size:11px;font-weight:750}.contact-consent{margin-top:20px;padding:18px;border-radius:12px;background:#f1f6fa}.contact-consent p{font-size:12px;line-height:1.6}.report-link{display:inline-flex;margin-top:18px;color:#174f78;font-weight:800}.match-chat{margin-top:24px;padding-top:22px;border-top:1px solid #dce5eb}.match-chat-log{display:grid;gap:10px;max-height:420px;overflow:auto;padding:15px;background:#f3f7fa;border-radius:12px}.match-chat-log article{max-width:78%;padding:11px 13px;border-radius:12px;background:#fff}.match-chat-log article.own{justify-self:end;background:#dceafd}.match-chat-log span,.match-chat-log small{font-size:9px;color:#617480}.match-chat-log p{margin:5px 0;white-space:pre-wrap}.match-chat form{display:grid;gap:9px;margin-top:13px}.match-chat textarea{padding:12px;border:1px solid #cddae3;border-radius:10px;resize:vertical}.match-chat button{justify-self:start}`}</style></div>;
}
