import type {Metadata} from "next";
import {ConversionCta,SiteFooter,SiteHeader} from "../components/site-chrome";
import {PublicSignupLink} from "../components/public-signup-link";
export const metadata:Metadata={title:"Was Sie beim Rechtsfall Check erhalten",description:"Ihr Rechtsproblem verständlich vorprüfen: mit geführter Fallaufnahme, Dokumentenanalyse, passenden Rückfragen und klaren nächsten Prüfschritten.",alternates:{canonical:"/rechtsfall-check"}};
export default function CheckPage(){return <div className="site"><SiteHeader/><main><section className="subhero product-subhero"><div><span className="section-label light-label">MEHR ALS EINE EINFACHE KI-ANTWORT</span><h1>Ihr Fall wird Schritt für Schritt aufbereitet.</h1><p>Sie schildern das Problem, laden Unterlagen hoch und beantworten bei Bedarf kurze Rückfragen.</p><PublicSignupLink className="button button-light">Kostenlose Fallakte anlegen →</PublicSignupLink></div></section>
<section className="content-split section-wrap"><div><span className="section-label">DAS SYSTEM HINTER DEM CHECK</span><h2>Ihre Angaben und Unterlagen werden zusammen betrachtet.</h2></div><div><p>Der Rechtsfall Check sammelt alles an einem geschützten Ort: Ihre Schilderung, Ihre Dokumente und Ihre Antworten. So wird sichtbar, welche Aussagen belegt sind und wo noch etwas fehlt.</p><p>Geprüfte Gesetzesquellen und feste Qualitätsregeln begrenzen die Analyse. Kann etwas nicht zuverlässig eingeordnet werden, zeigt das Ergebnis diese Unsicherheit deutlich.</p></div></section>
<section className="feature-detail section-wrap"><article><span>01</span><div><h3>Verständliche Fallaufnahme</h3><p>Sie geben Beteiligte, Ereignisse, Daten, Beträge und Ihr gewünschtes Ergebnis ohne juristische Fachbegriffe an.</p></div></article><article><span>02</span><div><h3>Unterlagen werden gelesen</h3><p>Verträge, Rechnungen, Schreiben und Bilder werden sicher verarbeitet und den passenden Angaben zugeordnet.</p></div></article><article><span>03</span><div><h3>Passende Rückfragen</h3><p>Statt allgemeiner Fragen erhalten Sie nur Rückfragen, die für Ihren konkreten Fall noch wichtig sind.</p></div></article><article><span>04</span><div><h3>Geprüfte Grenzen</h3><p>Das System macht fehlende Angaben und mögliche Fristen sichtbar, statt eine scheinbar sichere Antwort zu erfinden.</p></div></article><article><span>05</span><div><h3>Ihr finaler Rechtsfall Check</h3><p>Sie erhalten eine klare Zusammenfassung mit Fakten, offenen Punkten, möglichen Prüfgrundlagen und sinnvollen nächsten Schritten.</p></div></article></section>
<section className="deliverable section-wrap"><div className="deliverable-preview"><small>ERGEBNIS IHRES RECHTSFALL CHECKS</small><h3>Strukturierte Ersteinschätzung</h3>{["Kurzfassung Ihres Falls","Belegte Fakten und Dokumente","Offene Fragen und fehlende Nachweise","Mögliche Fristen und Rechtsgrundlagen","Risiken, Gegenargumente und Prüfbedarf","Hinweis, wann anwaltliche Hilfe nötig ist"].map(x=><span key={x}>✓ {x}</span>)}</div><div><span className="section-label">IHR MEHRWERT</span><h2>Besser vorbereitet in jede weitere Entscheidung.</h2><p>Wenn anwaltliche Hilfe notwendig ist, gehen Sie mit einer strukturierten Fallakte und klaren offenen Fragen in das Gespräch. Das kann die Erstaufnahme effizienter machen.</p><p>Wenn Informationen fehlen, wissen Sie konkret, was Sie noch zusammentragen sollten.</p></div></section>
<section className="legal-boundary-box section-wrap"><strong>Was der Rechtsfall Check bewusst nicht ist</strong><p>Keine Kanzlei, keine Rechtsvertretung, keine verbindliche Anspruchsfeststellung und keine Garantie für einen bestimmten Ausgang. Das Ergebnis ist eine nicht abschließende Ersteinschätzung.</p></section><ConversionCta/><SiteFooter/></main></div>}
