import type {Metadata} from "next";
import Link from "next/link";
import {ConversionCta,SiteFooter,SiteHeader} from "../components/site-chrome";
export const metadata:Metadata={title:"Das Analysetool für Ihren Rechtsfall",description:"Rechtsfall Check verbindet geführte Fallaufnahme, Dokumentenanalyse, interaktive KI, offizielle Gesetzesquellen und Qualitätsgates.",alternates:{canonical:"/rechtsfall-check"}};
export default function CheckPage(){return <div className="site"><SiteHeader/><main><section className="subhero product-subhero"><div><span className="section-label light-label">MEHR ALS EINE KI-ANTWORT</span><h1>Ein vollständiges Analysetool für Ihren Rechtsfall.</h1><p>Fallaufnahme, Unterlagen, gezielte Rückfragen und Rechtsquellen arbeiten in einem geführten Prozess zusammen.</p><Link href="/anmelden?mode=signup" className="button button-light">Rechtsfall Check starten →</Link></div></section>
<section className="content-split section-wrap"><div><span className="section-label">DAS SYSTEM HINTER DEM CHECK</span><h2>Ihr Fall wird nicht nur gelesen. Er wird strukturiert geprüft.</h2></div><div><p>Der Rechtsfall Check führt Ihre Schilderung, Dokumente und Antworten in einer geschützten digitalen Fallakte zusammen. Die Software trennt Angaben von Belegen, erkennt Informationslücken und gleicht mögliche Widersprüche ab.</p><p>Die KI arbeitet dabei nicht isoliert: Offizielle Gesetzesquellen, definierte Prüfregeln, Fristenhinweise und Qualitätsgates begrenzen die Ausgabe. Wo eine verlässliche Einordnung nicht möglich ist, zeigt das System die Unsicherheit offen an.</p></div></section>
<section className="feature-detail section-wrap"><article><span>01</span><div><h3>Geführte Fallaufnahme</h3><p>Verständliche Eingaben erfassen Beteiligte, Ereignisse, Daten, Beträge, Kommunikation und Ihr gewünschtes Ergebnis.</p></div></article><article><span>02</span><div><h3>OCR-, Dokumenten- und Beleganalyse</h3><p>Verträge, Rechnungen, Schreiben und Bilder werden sicher verarbeitet, ausgelesen und Aussagen im Fall nachvollziehbar zugeordnet.</p></div></article><article><span>03</span><div><h3>Fallbezogene KI-Interaktion</h3><p>Statt allgemeiner Standardfragen entstehen gezielte Rückfragen aus Ihrem Sachverhalt und der vorhandenen Dokumentenlage.</p></div></article><article><span>04</span><div><h3>Quellen- und Qualitätsprüfung</h3><p>Offizielle Gesetzesquellen, Fristenmodule und Nicht-Antwort-Regeln verhindern, dass aus fehlenden Angaben scheinbar sichere Aussagen entstehen.</p></div></article><article><span>05</span><div><h3>Finaler Rechtsfall Check</h3><p>Nach Abschluss der Angaben erhalten Sie eine einzige finale Zusammenfassung mit Fakten, Unsicherheiten, Prüfgrundlagen und nächstem sinnvollen Schritt.</p></div></article></section>
<section className="deliverable section-wrap"><div className="deliverable-preview"><small>ERGEBNIS IHRES RECHTSFALL CHECKS</small><h3>Strukturierte Ersteinschätzung</h3>{["Kurzfassung Ihres Falls","Belegte Fakten und Dokumente","Offene Fragen und fehlende Nachweise","Mögliche Fristen und Rechtsgrundlagen","Risiken, Gegenargumente und Prüfbedarf","Hinweis, wann anwaltliche Hilfe nötig ist"].map(x=><span key={x}>✓ {x}</span>)}</div><div><span className="section-label">IHR MEHRWERT</span><h2>Besser vorbereitet in jede weitere Entscheidung.</h2><p>Wenn anwaltliche Hilfe notwendig ist, gehen Sie mit einer strukturierten Fallakte und klaren offenen Fragen in das Gespräch. Das kann die Erstaufnahme effizienter machen.</p><p>Wenn Informationen fehlen, wissen Sie konkret, was Sie noch zusammentragen sollten.</p></div></section>
<section className="legal-boundary-box section-wrap"><strong>Was der Rechtsfall Check bewusst nicht ist</strong><p>Keine Kanzlei, keine Rechtsvertretung, keine verbindliche Anspruchsfeststellung und keine Garantie für einen bestimmten Ausgang. Das Ergebnis ist eine nicht abschließende Ersteinschätzung.</p></section><ConversionCta/><SiteFooter/></main></div>}
