import type {Metadata} from "next";
import Link from "next/link";
import {ConversionCta,SiteFooter,SiteHeader} from "../components/site-chrome";
export const metadata:Metadata={title:"Der Rechtsfall Check",description:"Leistungsumfang des Rechtsfall Checks: strukturierte Fallaufnahme, Dokumentenanalyse, Rückfragen und nicht abschließende Ersteinschätzung.",alternates:{canonical:"/rechtsfall-check"}};
export default function CheckPage(){return <div className="site"><SiteHeader/><main><section className="subhero product-subhero"><div><span className="section-label light-label">DAS PRODUKT</span><h1>Der Rechtsfall Check.</h1><p>Eine verständliche Vorprüfung zwischen eigener Internetrecherche und anwaltlicher Beratung.</p><Link href="/anmelden?mode=signup" className="button button-light">Rechtsfall Check starten →</Link></div></section>
<section className="content-split section-wrap"><div><span className="section-label">WAS SIE ERHALTEN</span><h2>Ihr Fall – strukturiert, nachvollziehbar und vorbereitet.</h2></div><div><p>Der Rechtsfall Check führt Ihre Schilderung und Dokumente in einer digitalen Fallakte zusammen. Das Ergebnis trennt belegte Tatsachen, offene Angaben, mögliche Rechtsgrundlagen und den weiteren Prüfbedarf.</p><p>Damit verstehen Sie schneller, worum es rechtlich gehen könnte und welche Informationen für den nächsten Schritt wichtig sind.</p></div></section>
<section className="feature-detail section-wrap"><article><span>01</span><div><h3>Geführte Fallaufnahme</h3><p>Sie müssen keine juristischen Begriffe kennen. Verständliche Fragen erfassen Parteien, Ereignisse, Daten, Beträge und bisherige Kommunikation.</p></div></article><article><span>02</span><div><h3>Dokumenten- und Belegstruktur</h3><p>Verträge, Rechnungen, Schreiben, Fotos und E-Mails werden der Fallakte zugeordnet. Wichtige Aussagen erhalten einen nachvollziehbaren Belegstatus.</p></div></article><article><span>03</span><div><h3>Intelligente Rückfragen</h3><p>Fehlende Angaben und mögliche Widersprüche werden sichtbar, bevor eine Einordnung erstellt wird.</p></div></article><article><span>04</span><div><h3>Ersteinschätzung</h3><p>Sie erhalten eine verständliche Zusammenfassung, mögliche Prüfgrundlagen, Unsicherheiten und klare Hinweise auf den weiteren Prüfbedarf.</p></div></article></section>
<section className="deliverable section-wrap"><div className="deliverable-preview"><small>ERGEBNIS IHRES RECHTSFALL CHECKS</small><h3>Strukturierte Ersteinschätzung</h3>{["Kurzfassung Ihres Falls","Belegte Fakten und Dokumente","Offene Fragen und fehlende Nachweise","Mögliche Fristen und Rechtsgrundlagen","Risiken, Gegenargumente und Prüfbedarf","Hinweis, wann anwaltliche Hilfe nötig ist"].map(x=><span key={x}>✓ {x}</span>)}</div><div><span className="section-label">IHR MEHRWERT</span><h2>Besser vorbereitet in jede weitere Entscheidung.</h2><p>Wenn anwaltliche Hilfe notwendig ist, gehen Sie mit einer strukturierten Fallakte und klaren offenen Fragen in das Gespräch. Das kann die Erstaufnahme effizienter machen.</p><p>Wenn Informationen fehlen, wissen Sie konkret, was Sie noch zusammentragen sollten.</p></div></section>
<section className="legal-boundary-box section-wrap"><strong>Was der Rechtsfall Check bewusst nicht ist</strong><p>Keine Kanzlei, keine Rechtsvertretung, keine verbindliche Anspruchsfeststellung und keine Garantie für einen bestimmten Ausgang. Das Ergebnis ist eine nicht abschließende Ersteinschätzung.</p></section><ConversionCta/><SiteFooter/></main></div>}
