import type { Metadata } from "next";
import Link from "next/link";
import { ConversionCta,SiteFooter,SiteHeader } from "./components/site-chrome";
import { legalAreas } from "../lib/legal-areas";
import { getSiteUrl } from "../lib/site-url";

export const metadata:Metadata={title:"Rechtsfall Check – Klarheit für Ihren Rechtsfall",description:"Ihr Rechtsfall Check für 19 €: Fall schildern, Unterlagen hochladen und eine strukturierte Vorprüfung mit klaren nächsten Prüfschritten erhalten.",alternates:{canonical:"/"}};
const claim="Klarheit, bevor Sie zum Anwalt gehen.";

export default function Home(){
  const siteUrl=getSiteUrl();
  const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":`${siteUrl}/#organization`,name:"Rechtsfall Check",url:siteUrl},{"@type":"Service","@id":`${siteUrl}/#check`,name:"Rechtsfall Check",description:"KI-gestützte Vorprüfung eines Rechtsfalls mit strukturierter Ersteinschätzung.",areaServed:"DE",provider:{"@id":`${siteUrl}/#organization`},offers:{"@type":"Offer",price:"39.00",priceCurrency:"EUR"}}]};
  return <div className="site"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><SiteHeader/><main>
    <section className="hero-v2">
      <div className="hero-v2-shade"/>
      <div className="hero-v2-content"><div className="trust-pill dark-pill"><span>●</span> Digitaler Rechtsfall Check · Deutschland</div><h1>Ihr Fall.<br/><em>Klar vorgeprüft.</em></h1><p className="hero-claim">{claim}</p><p className="hero-v2-lead">Sie schildern, was passiert ist, und laden Ihre Unterlagen hoch. Unser Rechtsfall Check strukturiert den Sachverhalt, erkennt offene Punkte und zeigt Ihnen verständlich, welche nächsten Schritte geprüft werden sollten.</p><div className="hero-buttons"><Link href="/anmelden?mode=signup" className="button button-large">Rechtsfall Check starten <b>→</b></Link><Link href="/so-funktionierts" className="hero-ghost">Ablauf ansehen</Link></div><div className="hero-assurances hero-assurances-light"><span>✓ Einmalig 19 €</span><span>✓ Kein Abo</span><span>✓ Ergebnis im Nutzerkonto</span></div></div>
      <div className="hero-float-card"><small>IHR RECHTSFALL CHECK</small><strong>Struktur statt Unsicherheit</strong><div><span>✓ Sachverhalt geordnet</span><span>✓ Unterlagen einbezogen</span><span>✓ Nächste Prüfschritte erklärt</span></div></div>
    </section>

    <section className="comparison-ribbon"><div><small>RECHTSFALL CHECK</small><strong>19 €</strong><span>je Fall, kein Abo</span></div><i>statt direkt in eine kostenintensivere Beratung zu starten</i><div><small>ANWALTLICHES ERSTGESPRÄCH</small><strong>bis 190 €*</strong><span>zzgl. USt., sofern nichts vereinbart</span></div><p>* Gesetzlicher Höchstbetrag für Verbraucher ohne Vergütungsvereinbarung nach § 34 RVG. Der Rechtsfall Check ist keine anwaltliche Erstberatung.</p></section>

    <section className="section-wrap value-intro"><div><span className="section-label">DER SCHNELLE ERSTE SCHRITT</span><h2>Erst verstehen.<br/>Dann gezielt entscheiden.</h2></div><div><p>Viele Menschen wissen nicht, ob ihr Fall rechtlich relevant ist, welche Unterlagen zählen oder ob der Gang zum Anwalt sinnvoll ist. Genau hier setzt der Rechtsfall Check an.</p><Link href="/rechtsfall-check" className="inline-arrow">Was der Rechtsfall Check liefert →</Link></div></section>

    <section className="journey-section section-wrap"><div className="section-heading centered"><span className="section-label">IHRE CUSTOMER JOURNEY</span><h2>In vier klaren Schritten zum Ergebnis.</h2><p>Ein geführter Prozess – verständlich, transparent und ohne Juristendeutsch.</p></div><div className="journey-cards"><article><b>01</b><i>✎</i><h3>Konto erstellen</h3><p>Registrieren Sie sich kostenlos und legen Sie Ihre geschützte Fallakte an.</p></article><article><b>02</b><i>↥</i><h3>Fall &amp; Unterlagen</h3><p>Beschreiben Sie den Fall und laden Sie Verträge, Schreiben oder Belege hoch.</p></article><article><b>03</b><i>✦</i><h3>Rechtsfall Check</h3><p>Die KI strukturiert Fakten, Dokumente, Widersprüche und offene Fragen.</p></article><article><b>04</b><i>→</i><h3>Klare nächste Schritte</h3><p>Sie erhalten eine verständliche Einordnung und Hinweise zum weiteren Prüfbedarf.</p></article></div><div className="center-link"><Link href="/so-funktionierts" className="button-secondary">Den vollständigen Ablauf ansehen →</Link></div></section>

    <section className="areas-preview"><div className="section-wrap"><div className="areas-head"><div><span className="section-label light-label">VIELE RECHTSGEBIETE · EIN EINSTIEG</span><h2>Welches rechtliche Problem beschäftigt Sie?</h2></div><p>Von Arbeits- und Mietrecht über Nachbarschafts-, Vertrags- und Verbraucherfragen bis zu Behörden-, Familien- oder Strafsachen: Die geführte Fallaufnahme stellt die passenden Themen und Hilfestellungen bereit.</p></div><div className="area-mini-grid">{legalAreas.slice(0,8).map(area=><Link href={`/rechtsgebiete#${area.slug}`} key={area.slug}><i>{area.icon}</i><span><strong>{area.title}</strong><small>{area.examples}</small></span><b>→</b></Link>)}</div><Link href="/rechtsgebiete" className="button button-light all-areas">Alle Rechtsgebiete entdecken →</Link></div></section>

    <section className="benefits section-wrap"><div className="section-heading"><span className="section-label">IHR ERGEBNIS</span><h2>Keine Blackbox.<br/>Ein nachvollziehbarer Rechtsfall Check.</h2></div><div className="benefit-grid"><article><i>✓</i><h3>Was belegt ist</h3><p>Welche Tatsachen durch Ihre Angaben oder Dokumente gestützt werden.</p></article><article><i>?</i><h3>Was noch fehlt</h3><p>Welche Rückfragen und Unterlagen für eine bessere Einordnung wichtig sind.</p></article><article><i>§</i><h3>Was relevant sein kann</h3><p>Welche geprüften Rechtsgrundlagen und Fristen grundsätzlich in Betracht kommen.</p></article><article><i>→</i><h3>Was als Nächstes zählt</h3><p>Ob weitere Informationen, eine Fristprüfung oder anwaltliche Hilfe angezeigt ist.</p></article></div></section>

    <section className="responsible section-wrap"><div><span className="section-label">KLARE GRENZEN SCHAFFEN VERTRAUEN</span><h2>Eine Vorprüfung, keine Schein­sicherheit.</h2></div><div><p>Der Rechtsfall Check liefert eine strukturierte, nicht abschließende Ersteinschätzung. Er ersetzt keine anwaltliche Beratung und gibt keine verbindliche Rechts- oder Handlungsanweisung.</p><p>Bei hoher Tragweite, unklaren Fristen, Strafsachen oder fehlenden Kerninformationen wird nicht spekuliert. Stattdessen zeigt das Ergebnis transparent, warum eine anwaltliche Prüfung erforderlich ist.</p><Link href="/sicherheit" className="inline-arrow">Sicherheit und Qualitätsregeln →</Link></div></section>
    <ConversionCta/>
  </main><SiteFooter/></div>
}
