import type { Metadata } from "next";
import Link from "next/link";
import { ConversionCta,SiteFooter,SiteHeader } from "./components/site-chrome";
import { legalAreas } from "../lib/legal-areas";
import { getSiteUrl } from "../lib/site-url";

export const metadata:Metadata={title:"Rechtsfall Check – Digitale Fallanalyse für 19 €",description:"Das digitale Analysetool für Ihren Rechtsfall: Sachverhalt erfassen, Dokumente auswerten, gezielte Rückfragen beantworten und eine nachvollziehbare Einordnung erhalten.",alternates:{canonical:"/"}};
const claim="Ihr Fall. Systematisch analysiert. Verständlich eingeordnet.";

export default function Home(){
  const siteUrl=getSiteUrl();
  const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":`${siteUrl}/#organization`,name:"Rechtsfall Check",url:siteUrl},{"@type":"Service","@id":`${siteUrl}/#check`,name:"Rechtsfall Check",description:"Digitales Analysetool für Rechtsfälle mit geführter Fallaufnahme, Dokumentenauswertung und nachvollziehbarer Ersteinschätzung.",areaServed:"DE",provider:{"@id":`${siteUrl}/#organization`},offers:{"@type":"Offer",price:"19.00",priceCurrency:"EUR"}}]};
  return <div className="site"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/><SiteHeader/><main>
    <section className="hero-v2">
      <div className="hero-v2-shade"/>
      <div className="hero-v2-content"><div className="trust-pill dark-pill"><span>●</span> Digitales Rechtsanalyse-Tool · Deutschland</div><h1>Mehr als KI.<br/><em>Ein System für Ihren Fall.</em></h1><p className="hero-claim">{claim}</p><p className="hero-v2-lead">Der Rechtsfall Check verbindet Ihre Schilderung, hochgeladene Unterlagen, intelligente Rückfragen und offizielle Gesetzesquellen zu einer nachvollziehbaren Fallanalyse – ohne Juristendeutsch und ohne Abo.</p><div className="hero-buttons"><Link href="/anmelden?mode=signup" className="button button-large">Rechtsfall Check starten <b>→</b></Link><Link href="/so-funktionierts" className="hero-ghost">Analyseprozess ansehen</Link></div><div className="hero-assurances hero-assurances-light"><span>✓ Einmalig 19 €</span><span>✓ Geschützter Fallraum</span><span>✓ Keine erfundene Sicherheit</span></div></div>
      <div className="hero-float-card"><small>IHR RECHTSFALL CHECK</small><strong>Struktur statt Unsicherheit</strong><div><span>✓ Sachverhalt geordnet</span><span>✓ Unterlagen einbezogen</span><span>✓ Nächste Prüfschritte erklärt</span></div></div>
    </section>

    <section className="comparison-ribbon"><div><small>RECHTSFALL CHECK</small><strong>19 €</strong><span>je Fall, kein Abo</span></div><i>statt direkt in eine kostenintensivere Beratung zu starten</i><div><small>ANWALTLICHES ERSTGESPRÄCH</small><strong>bis 190 €*</strong><span>zzgl. USt., sofern nichts vereinbart</span></div><p>* Gesetzlicher Höchstbetrag für Verbraucher ohne Vergütungsvereinbarung nach § 34 RVG. Der Rechtsfall Check ist keine anwaltliche Erstberatung.</p></section>

    <section className="section-wrap value-intro"><div><span className="section-label">DAS ANALYSESYSTEM</span><h2>Nicht einfach fragen.<br/>Den Fall wirklich aufbereiten.</h2></div><div><p>Eine einzelne KI-Antwort kennt häufig weder die vollständige Dokumentenlage noch offene Widersprüche. Der Rechtsfall Check führt deshalb Schritt für Schritt durch Sachverhalt, Nachweise und gezielte Rückfragen. Erst wenn die erforderlichen Informationen vorliegen, wird der finale Check erstellt.</p><Link href="/rechtsfall-check" className="inline-arrow">Was im Rechtsfall Check geprüft wird →</Link></div></section>

    <section className="benefits section-wrap"><div className="section-heading"><span className="section-label">TECHNIK, DIE ZUSAMMENARBEITET</span><h2>Fünf Bausteine.<br/>Eine nachvollziehbare Fallanalyse.</h2></div><div className="benefit-grid"><article><i>01</i><h3>Geführter Sachverhalt</h3><p>Die Software erfasst Ereignisse, Beteiligte, Beträge, Ziele und zeitliche Abläufe strukturiert.</p></article><article><i>02</i><h3>Dokumentenanalyse</h3><p>PDFs, Schreiben und Bilder werden sicher geprüft, ausgelesen und dem Fall zugeordnet.</p></article><article><i>03</i><h3>Interaktive KI</h3><p>Die KI erkennt Informationslücken und stellt nur die Rückfragen, die für den konkreten Fall noch wichtig sind.</p></article><article><i>04</i><h3>Rechtsquellen &amp; Fristen</h3><p>Offizielle Gesetzesquellen und definierte Qualitätsregeln begrenzen die Analyse und machen Unsicherheiten sichtbar.</p></article></div></section>

    <section className="journey-section section-wrap"><div className="section-heading centered"><span className="section-label">SO ENTSTEHT IHR ERGEBNIS</span><h2>Vom Problem zur belastbaren Übersicht.</h2><p>Kein spontaner Chat. Ein geführter, mehrstufiger Analyseprozess.</p></div><div className="journey-cards"><article><b>01</b><i>✎</i><h3>Fall erfassen</h3><p>Sie schildern den Ablauf in Ihren Worten und bestimmen, was Sie erreichen möchten.</p></article><article><b>02</b><i>↥</i><h3>Nachweise verbinden</h3><p>Verträge, Schreiben, Belege und Korrespondenz ergänzen Ihre Angaben.</p></article><article><b>03</b><i>✦</i><h3>Analyse vertiefen</h3><p>Das System gleicht Fakten und Unterlagen ab und fragt nur bei entscheidenden Lücken nach.</p></article><article><b>04</b><i>→</i><h3>Finalen Check erhalten</h3><p>Sie erhalten eine verständliche Zusammenfassung, Prüfhinweise und den sinnvollsten nächsten Schritt.</p></article></div><div className="center-link"><Link href="/so-funktionierts" className="button-secondary">Den vollständigen Analyseprozess ansehen →</Link></div></section>

    <section className="benefits section-wrap"><div className="section-heading"><span className="section-label">TYPISCHE ANWENDUNGSSITUATIONEN</span><h2>Wobei der Rechtsfall Check Orientierung schafft.</h2><p>Beispiele für typische Ausgangslagen – keine erfundenen Kundenstimmen.</p></div><div className="benefit-grid"><article><i>?</i><h3>„Ist das überhaupt rechtlich relevant?“</h3><p>Der Check ordnet den Sachverhalt und zeigt, welche Tatsachen und Grundlagen genauer geprüft werden sollten.</p></article><article><i>≡</i><h3>„Welche Unterlagen zählen?“</h3><p>Die Analyse trennt vorhandene Nachweise von noch fehlenden Informationen.</p></article><article><i>!</i><h3>„Gibt es ein Fristenrisiko?“</h3><p>Mögliche zeitkritische Punkte werden sichtbar gemacht – ohne eine verbindliche Fristenkontrolle vorzutäuschen.</p></article><article><i>→</i><h3>„Was ist jetzt sinnvoll?“</h3><p>Das Ergebnis zeigt den nächsten Prüfbedarf und wann anwaltliche Unterstützung angezeigt ist.</p></article></div></section>

    <section className="areas-preview"><div className="section-wrap"><div className="areas-head"><div><span className="section-label light-label">VIELE RECHTSGEBIETE · EIN EINSTIEG</span><h2>Welches rechtliche Problem beschäftigt Sie?</h2></div><p>Von Arbeits- und Mietrecht über Nachbarschafts-, Vertrags- und Verbraucherfragen bis zu Behörden-, Familien- oder Strafsachen: Die geführte Fallaufnahme stellt die passenden Themen und Hilfestellungen bereit.</p></div><div className="area-mini-grid">{legalAreas.slice(0,8).map(area=><Link href={`/rechtsgebiete#${area.slug}`} key={area.slug}><i>{area.icon}</i><span><strong>{area.title}</strong><small>{area.examples}</small></span><b>→</b></Link>)}</div><Link href="/rechtsgebiete" className="button button-light all-areas">Alle Rechtsgebiete entdecken →</Link></div></section>

    <section className="benefits section-wrap"><div className="section-heading"><span className="section-label">IHR ERGEBNIS</span><h2>Keine Blackbox.<br/>Ein nachvollziehbarer Rechtsfall Check.</h2></div><div className="benefit-grid"><article><i>✓</i><h3>Was belegt ist</h3><p>Welche Tatsachen durch Ihre Angaben oder Dokumente gestützt werden.</p></article><article><i>?</i><h3>Was noch fehlt</h3><p>Welche Rückfragen und Unterlagen für eine bessere Einordnung wichtig sind.</p></article><article><i>§</i><h3>Was relevant sein kann</h3><p>Welche geprüften Rechtsgrundlagen und Fristen grundsätzlich in Betracht kommen.</p></article><article><i>→</i><h3>Was als Nächstes zählt</h3><p>Ob weitere Informationen, eine Fristprüfung oder anwaltliche Hilfe angezeigt ist.</p></article></div></section>

    <section className="responsible section-wrap"><div><span className="section-label">KLARE GRENZEN SCHAFFEN VERTRAUEN</span><h2>Eine Vorprüfung, keine Schein­sicherheit.</h2></div><div><p>Der Rechtsfall Check liefert eine strukturierte, nicht abschließende Ersteinschätzung. Er ersetzt keine anwaltliche Beratung und gibt keine verbindliche Rechts- oder Handlungsanweisung.</p><p>Bei hoher Tragweite, unklaren Fristen, Strafsachen oder fehlenden Kerninformationen wird nicht spekuliert. Stattdessen zeigt das Ergebnis transparent, warum eine anwaltliche Prüfung erforderlich ist.</p><Link href="/sicherheit" className="inline-arrow">Sicherheit und Qualitätsregeln →</Link></div></section>
    <ConversionCta/>
  </main><SiteFooter/></div>
}
