"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
type Result={summary:string;facts:string[];missing:string[];sources:string[];gate:string};
export function CaseWorkspace({userName,caseId}:{userName:string;caseId:string}){
  const[busy,setBusy]=useState(false);const[result,setResult]=useState<Result|null>(null);const[file,setFile]=useState("");const[paid,setPaid]=useState(false);const[caseTitle,setCaseTitle]=useState("Ihre Fallakte");const[error,setError]=useState("");
  useEffect(()=>{fetch(`/api/v1/cases/${caseId}`,{cache:"no-store"}).then(r=>r.json()).then(data=>{setPaid(data.case?.paymentStatus==="PAID");setCaseTitle(data.case?.title||"Ihre Fallakte")}).catch(()=>setError("Falldaten konnten nicht geladen werden."))},[caseId]);
  async function checkout(){setBusy(true);setError("");const response=await fetch("/api/v1/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId})});const data=await response.json();if(response.ok&&data.url){window.location.href=data.url;return}setError(data.error?.message||"Die Zahlung konnte nicht gestartet werden.");setBusy(false)}
  async function analyze(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!paid){await checkout();return}setBusy(true);setResult(null);setError("");const form=new FormData(event.currentTarget);const selected=(document.getElementById("document") as HTMLInputElement)?.files?.[0];if(selected){const upload=new FormData();upload.set("file",selected);const uploadResponse=await fetch(`/api/v1/cases/${caseId}/documents`,{method:"POST",body:upload});if(!uploadResponse.ok){setError("Die Datei konnte nicht sicher gespeichert werden. Bitte prüfen Sie Dateityp und Größe.");setBusy(false);return}}
    const response=await fetch("/api/v1/assessments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId,topic:form.get("topic"),eventDate:form.get("eventDate"),description:form.get("description"),hasDocument:Boolean(selected),aiConsent:form.get("aiConsent")==="on"})});const data=await response.json();if(!response.ok){setError(data.error?.message||"Die Analyse konnte nicht erstellt werden.");setBusy(false);return}setResult(data);setBusy(false)}
  return <div className="app-shell">
    <header className="member-nav"><Link href="/" className="logo"><span>R</span><strong>Rechtsfall</strong><em>KI</em></Link><div><Link href="/fallraum">Meine Fälle</Link><Link className="profile-link" href="/profil">{userName}</Link></div></header>
    <div className="app-layout"><aside className="app-sidebar"><Link href="/fallraum">← Zur Fallübersicht</Link><ol className="app-steps"><li className="active"><b>1</b>Fall beschreiben</li><li><b>2</b>Unterlagen ergänzen</li><li><b>3</b>Rückfragen klären</li><li><b>4</b>Ersteinschätzung</li></ol></aside>
      <main className="app-content"><span className="section-label">FALLAKTE · KAUFRECHT</span><h1>{caseTitle}</h1><p className="lead">Beschreiben Sie den Ablauf so, wie Sie ihn erlebt haben. Sie müssen keine juristischen Begriffe verwenden.</p>
        {!paid&&<section className="paywall"><div><strong>Fallprüfung freischalten</strong><p>Vollständige Analyse, Dokumentenprüfung und Ergebnis – einmalig 39 €, kein Abo.</p></div><button className="button" onClick={checkout} disabled={busy}>{busy?"Zahlung wird geöffnet …":"Für 39 € freischalten →"}</button></section>}
        {error&&<p className="auth-error">{error}</p>}
        <form className="app-card" onSubmit={analyze}><div className="app-grid">
          <div className="field"><label htmlFor="topic">Worum geht es?</label><select id="topic" name="topic" defaultValue="Mangelhafte Ware / Kaufvertrag"><option>Mangelhafte Ware / Kaufvertrag</option></select></div>
          <div className="field"><label htmlFor="eventDate">Wann ist es passiert?</label><input id="eventDate" name="eventDate" type="date" required/></div>
          <div className="field full"><label htmlFor="description">Was ist genau passiert?</label><textarea id="description" name="description" required placeholder="Beispiel: Ich habe am 12. Mai ein Notebook bestellt. Nach drei Tagen ließ es sich nicht mehr einschalten. Der Händler hat auf meine E-Mail bisher nicht reagiert …"/></div>
          <div className="field full"><label>Unterlagen zu diesem Fall</label><label className="upload-zone" htmlFor="document"><span>↥</span><span><strong>{file||"PDF, Foto oder Schreiben auswählen"}</strong><small>PDF, JPG oder PNG · maximal 10 MB pro Datei</small></span></label><input className="hidden" id="document" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]?.name||"")}/></div>
          <label className="consent full"><input type="checkbox" name="aiConsent" required/><span>Ich stimme zu, dass meine Angaben zur Erstellung der Analyse durch den konfigurierten KI-Dienstleister verarbeitet werden. Details stehen in den Datenschutzhinweisen.</span></label>
        </div><div className="app-actions"><small>Ihre Angaben werden verschlüsselt übertragen und ausschließlich Ihrer Fallakte zugeordnet.</small><button className="button" disabled={busy}>{busy?"Fall wird analysiert …":paid?"Analyse starten →":"Fallprüfung freischalten →"}</button></div></form>
        {result&&<section className="result-grid" aria-live="polite"><div className="result-box"><h3>ERKANNTE FAKTEN</h3><ul>{result.facts.map(x=><li key={x}>{x}</li>)}</ul></div><div className="result-box"><h3>OFFENE FRAGEN</h3><ul>{result.missing.map(x=><li key={x}>{x}</li>)}</ul></div><div className="result-box"><h3>MÖGLICHE GRUNDLAGEN</h3><ul>{result.sources.map(x=><li key={x}>{x}</li>)}</ul></div><div className="result-box"><h3>QUALITÄTSPRÜFUNG</h3><p>{result.gate}</p></div><div className="result-box wide"><h3>IHRE VORLÄUFIGE ERSTEINSCHÄTZUNG</h3><p>{result.summary}</p><small>Die Ausgabe ersetzt keine anwaltliche Beratung. Keine verbindliche Handlungsanweisung und keine finale Einzelfallentscheidung.</small></div></section>}
      </main></div>
  </div>
}
