"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { authClient } from "@/lib/auth-client";
import { trackAnalyticsEvent } from "@/lib/analytics";

export function TwoFactorChallenge() {
  const [mode,setMode]=useState<"totp"|"backup">("totp"); const [code,setCode]=useState("");
  const [trustDevice,setTrustDevice]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");const result=mode==="totp"?await authClient.twoFactor.verifyTotp({code:code.replace(/\s/g,""),trustDevice}):await authClient.twoFactor.verifyBackupCode({code:code.trim(),trustDevice});setBusy(false);if(result.error){setError(result.error.status===429?"Zu viele Fehlversuche. Der Zugang ist vorübergehend gesperrt. Bitte versuchen Sie es später erneut.":"Der Sicherheitscode ist ungültig oder abgelaufen.");return}trackAnalyticsEvent("login",{method:"email_2fa"});const returnTo=sessionStorage.getItem("rechtsfall-check:returnTo")||"/fallraum";sessionStorage.removeItem("rechtsfall-check:returnTo");window.location.href=returnTo.startsWith("/")&&!returnTo.startsWith("//")?returnTo:"/fallraum"}
  return <><div className="auth-tabs" role="tablist" aria-label="Bestätigungsart"><button type="button" role="tab" aria-selected={mode==="totp"} className={mode==="totp"?"active":""} onClick={()=>{setMode("totp");setCode("");setError("")}}>Authenticator-Code</button><button type="button" role="tab" aria-selected={mode==="backup"} className={mode==="backup"?"active":""} onClick={()=>{setMode("backup");setCode("");setError("")}}>Wiederherstellungscode</button></div><form className="auth-form two-factor-challenge" onSubmit={submit} aria-busy={busy}><div className="field"><label htmlFor="securityCode">{mode==="totp"?"Sechsstelliger Sicherheitscode":"Wiederherstellungscode"}</label><input id="securityCode" autoFocus inputMode={mode==="totp"?"numeric":"text"} autoComplete="one-time-code" pattern={mode==="totp"?"[0-9]{6}":undefined} maxLength={mode==="totp"?6:32} value={code} onChange={event=>setCode(mode==="totp"?event.target.value.replace(/\D/g,""):event.target.value)} required placeholder={mode==="totp"?"123456":"XXXX-XXXX"}/></div><label className="consent"><input type="checkbox" checked={trustDevice} onChange={event=>setTrustDevice(event.target.checked)}/><span>Diesem privaten Gerät 30 Tage vertrauen</span></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="button auth-submit" disabled={busy||(mode==="totp"&&code.length!==6)}>{busy?"Code wird geprüft …":"Sicher anmelden →"}</button></form><Link className="forgot-password-link" href="/anmelden">Zurück zum Login</Link></>;
}
