import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "@/app/components/site-chrome";

export const metadata: Metadata = {
  title: "Anwaltsportal – regional passende Mandatsanfragen",
  description: "Kanzleiprofil anlegen, Zulassung prüfen lassen und nach Rechtsgebiet, Entfernung und Verfügbarkeit passenden Rechtsuchenden vorgeschlagen werden.",
  alternates: { canonical: "/fuer-anwaelte" },
};

const signup = "/anmelden?mode=signup&accountType=LAWYER&returnTo=%2Fanwalt";

export default function LawyerLandingPage() {
  return <div className="site lawyer-landing"><SiteHeader/><main>
    <section className="lawyer-public-hero">
      <div className="lawyer-public-hero-inner">
        <div><span className="section-label light-label">RECHTSFALL-CHECK.DE FÜR RECHTSANWÄLTE</span><h1>Passende Mandatsanfragen.<br/><em>Durch gezieltes Matching.</em></h1><p>Wir bringen Ihre Kanzlei mit Rechtsuchenden zusammen, deren geprüftes Anliegen zu Ihrem Rechtsgebiet und Tätigkeitsradius passt.</p><div className="lawyer-hero-actions"><Link className="button button-light" href={signup}>Kanzlei kostenlos registrieren →</Link><a className="lawyer-ghost-button" href="#ablauf">So funktioniert das Matching</a></div><div className="lawyer-hero-notes"><span>✓ Passende Rechtsgebiete</span><span>✓ Regional steuerbarer Radius</span><span>✓ Direkter Kontakt nach Nutzerauswahl</span></div></div>
        <aside><small>GEZIELT STATT ZUFÄLLIG</small><strong>Matching nach klaren Kriterien</strong><span>Rechtsgebiet · Entfernung · Verfügbarkeit</span><hr/><b>Vorqualifizierter Erstkontakt</b><p>Nach der Auswahl erhalten Sie den strukturierten Prüfbericht und können direkt mit dem Nutzer schreiben.</p><Link href="#matching">Matching im Detail ansehen →</Link></aside>
      </div>
    </section>

    <section className="lawyer-proof-strip"><div><span>01</span><strong>Geprüfte Anwaltsprofile</strong><p>Aktivierung erst nach Prüfung der Berufsberechtigung.</p></div><div><span>02</span><strong>Regelbasiertes Matching</strong><p>Rechtsgebiet, Entfernung und Mandatsbereitschaft entscheiden.</p></div><div><span>03</span><strong>Nutzer entscheidet selbst</strong><p>Keine Kontaktdaten und keine Fallansicht ohne aktive Freigabe.</p></div><div><span>04</span><strong>Direkter Austausch</strong><p>Geschützter Chat nach Auswahl durch den Nutzer.</p></div></section>

    <section className="section-wrap lawyer-intro"><div><span className="section-label">WARUM RECHTSFALL-CHECK.DE?</span><h2>Mehr als ein Kanzleiverzeichnis.</h2></div><div><p>Rechtsuchende wissen häufig noch nicht, welches Rechtsgebiet betroffen ist, welche Unterlagen wichtig sind oder wie sie ihren Fall verständlich schildern sollen. Rechtsfall-Check.de führt sie durch eine strukturierte Fallaufnahme, wertet vorhandene Unterlagen aus und erstellt eine nicht abschließende Ersteinschätzung.</p><p>Wenn anschließend anwaltliche Unterstützung sinnvoll ist, kann das System geeignete Kanzleien vorschlagen. Sie erhalten damit nicht einfach einen anonymen Datensatz, sondern – ausschließlich nach Freigabe – einen bereits strukturierten Prüfbericht und eine direkte Kontaktmöglichkeit.</p><div className="lawyer-honesty"><strong>Wichtig und transparent</strong><span>Das Portal garantiert weder eine bestimmte Anzahl an Kontakten noch den Abschluss eines Mandats. Die fachliche und wirtschaftliche Entscheidung über eine Mandatsannahme bleibt vollständig bei der Kanzlei.</span></div></div></section>

    <section id="ablauf" className="lawyer-flow"><div className="section-wrap"><div className="section-heading centered"><span className="section-label light-label">DER GESAMTE ABLAUF</span><h2>Vom kostenlosen Profil bis zum möglichen Mandat.</h2><p>Sie können das Angebot und Ihr späteres Profil vollständig kennenlernen, bevor Sie sich für den kostenpflichtigen Jahreszugang entscheiden.</p></div><div className="lawyer-flow-grid">
      <article><b>01</b><i>§</i><h3>Kostenlos registrieren</h3><p>Sie eröffnen zunächst ohne Zahlung ein persönliches Anwaltskonto.</p></article>
      <article><b>02</b><i>✎</i><h3>Profil ausarbeiten</h3><p>Kanzlei, Kurzprofil, Kontaktdaten, Tätigkeitsgebiete und Radius vollständig hinterlegen.</p></article>
      <article><b>03</b><i>✓</i><h3>Zulassung bestätigen</h3><p>Wir prüfen Ihre Berufsberechtigung, Kammerzugehörigkeit und zulässige Berufsbezeichnungen.</p></article>
      <article><b>04</b><i>◎</i><h3>Profilvorschau prüfen</h3><p>Sie sehen vor der Buchung, wie Ihr Profil später passenden Nutzern angezeigt wird.</p></article>
      <article><b>05</b><i>€</i><h3>Jahreszugang buchen</h3><p>Erst Ihre freiwillige Stripe-Zahlung aktiviert das geprüfte Profil für zwölf Monate.</p></article>
      <article><b>06</b><i>↔</i><h3>Passend vorgeschlagen werden</h3><p>Nur bezahlte Nutzerfälle mit übereinstimmendem Rechtsgebiet und passender Entfernung kommen infrage.</p></article>
      <article><b>07</b><i>●</i><h3>Nutzer eröffnet Kontakt</h3><p>Der Nutzer wählt Ihr Profil und stimmt der Weitergabe von Kontakt und Prüfbericht ausdrücklich zu.</p></article>
      <article><b>08</b><i>→</i><h3>Mandat eigenständig prüfen</h3><p>Im Chat klären Sie den Erstkontakt. Interessenkollision, Kapazität und Mandatsbedingungen prüfen Sie selbst.</p></article>
    </div></div></section>

    <section id="matching" className="section-wrap lawyer-matching"><div><span className="section-label">KEIN ZUFALL, KEIN OFFENES LEAD-BOARD</span><h2>Matching nach nachvollziehbaren Kriterien.</h2><p>Profile werden nicht verkauft, versteigert oder willkürlich priorisiert. Ein Vorschlag setzt mehrere gleichzeitig erfüllte Bedingungen voraus.</p></div><ol><li><span>01</span><div><strong>Bezahlter Rechtsfall-Check</strong><p>Vor Abschluss der 19-€-Buchung werden Nutzern keine Anwaltsprofile gezeigt.</p></div></li><li><span>02</span><div><strong>Passendes Rechtsgebiet</strong><p>Das ermittelte Rechtsgebiet muss zu den tatsächlich hinterlegten Tätigkeitsgebieten passen.</p></div></li><li><span>03</span><div><strong>Geografische Nähe</strong><p>Der Nutzerstandort muss innerhalb des selbst festgelegten Tätigkeitsradius der Kanzlei liegen.</p></div></li><li><span>04</span><div><strong>Geprüfter und bezahlter Zugang</strong><p>Zulassung, Vertragsstatus und Zahlungsstatus müssen aktiv sein.</p></div></li><li><span>05</span><div><strong>Aktuelle Mandatsbereitschaft</strong><p>Nur Kanzleien, die neue Anfragen annehmen, werden berücksichtigt.</p></div></li><li><span>06</span><div><strong>Freie Auswahl des Nutzers</strong><p>Der Nutzer vergleicht Profile und entscheidet ohne automatische Zuweisung.</p></div></li></ol></section>

    <section className="lawyer-profile-showcase"><div className="section-wrap"><div className="lawyer-demo-card"><header><i>§</i><div><small>GEPRÜFTES ANWALTSPROFIL</small><h3>Ihre Kanzlei</h3><span>Kanzleisitz · regionaler Tätigkeitsradius</span></div></header><p>Ihre persönliche Kurzbeschreibung erläutert Erfahrung, Arbeitsweise und Schwerpunkte. Nutzer können sich damit bewusst für einen Kontakt entscheiden.</p><div><b>Arbeitsrecht</b><b>Vertragsrecht</b><b>Mietrecht</b></div><footer><span>Kontaktdaten erst nach Auswahl sichtbar</span><button type="button" disabled>Nachricht an Kanzlei senden</button></footer></div><div><span className="section-label light-label">IHR PROFIL</span><h2>Aussagekräftig, professionell und vor der Buchung vollständig sichtbar.</h2><ul><li>Kanzleiname und Kanzleisitz</li><li>Name und geprüfte Berufsbezeichnung</li><li>Tätigkeitsgebiete und zulässige Fachanwaltsbezeichnungen</li><li>Individuell festgelegter Tätigkeitsradius</li><li>Persönliche Kurzbeschreibung und Arbeitsweise</li><li>Website und freigegebene Kanzleikontaktdaten</li><li>Geschützter Button zur Kontaktaufnahme</li></ul></div></div></section>

    <section className="section-wrap lawyer-data"><div><span className="section-label">VERTRAULICHKEIT UND KONTROLLE</span><h2>Keine offenen Leads. Keine öffentlichen Fallakten.</h2><p>Registrierte Kanzleien und ihre Profile sind nicht als öffentliches Anwaltsverzeichnis verfügbar. Nutzer sehen ein Profil nur innerhalb ihres geschützten Kontos und erst nach einem bezahlten Rechtsfall-Check, wenn die Matching-Kriterien erfüllt sind.</p></div><div className="lawyer-data-grid"><article><i>○</i><h3>Vor der Auswahl</h3><p>Die Kanzlei sieht weder den Nutzer noch den Fall. Der Nutzer sieht nur die für ihn passenden Profilinformationen.</p></article><article><i>✓</i><h3>Nach ausdrücklicher Freigabe</h3><p>Die ausgewählte Kanzlei erhält Kontaktdaten, den vollständigen Prüfbericht und Zugang zum gemeinsamen Chat.</p></article><article><i>×</i><h3>Kein automatisches Mandat</h3><p>Die Freigabe ist eine Kontaktanbahnung. Ein Mandatsverhältnis entsteht ausschließlich durch eine gesonderte Vereinbarung.</p></article><article><i>⌁</i><h3>Geschützte Kommunikation</h3><p>Chat und Prüfbericht sind nur für den konkreten Nutzer, die ausgewählte Kanzlei und berechtigte Betreiberzugriffe erreichbar.</p></article></div></section>

    <section className="lawyer-budget"><div className="section-wrap"><div><span className="section-label light-label">IHR BEITRAG ARBEITET DOPPELT</span><h2>Portalzugang und aktive Mandantengewinnung.</h2><p>Sie bezahlen nicht nur für die Nutzung einer Plattform und auch nicht für einen einzelnen Kontakt. Die Hälfte Ihres Beitrags wird garantiert als Mediabudget eingesetzt. Damit schalten wir gezielt Kampagnen, gewinnen neue Rechtsuchende für das Portal und schaffen die Grundlage für weitere passende Mandatsanfragen.</p><ul className="lawyer-budget-benefits"><li>50 % garantiertes Mediabudget</li><li>Kampagnen für relevante Rechtsgebiete und Regionen</li><li>Neue Nutzer werden strukturiert bis zum Matching geführt</li><li>Keine zusätzliche Vermittlungsgebühr pro Kontakt oder Mandat</li></ul><small>Die Kampagnen erhöhen Reichweite und Nachfragechancen. Eine bestimmte Anzahl von Kontakten oder Mandaten kann nicht garantiert werden.</small></div><div className="lawyer-budget-card"><div><small>MONATLICHER LEISTUNGSWERT</small><strong>490 €</strong><span>netto pro Monat · 12 Monate Laufzeit</span></div><p>Der Gesamtbetrag von 5.880 € netto wird für das Vertragsjahr im Voraus berechnet.</p><hr/><div><small>FÜR GEZIELTE WERBEKAMPAGNEN</small><strong>245 €</strong><span>netto pro Monat · 2.940 € garantiertes Mediabudget pro Vertragsjahr</span></div><div><small>FÜR PORTAL UND MATCHING-TECHNOLOGIE</small><strong>245 €</strong><span>netto pro Monat · 2.940 € Plattformvergütung pro Vertragsjahr</span></div><p>Kommt über das Matching ein Mandat zustande, fällt gegenüber Rechtsfall-Check.de keine zusätzliche Vermittlungs- oder Erfolgsgebühr an.</p></div></div></section>

    <section className="section-wrap lawyer-contract"><div><span className="section-label">VERTRAGLICHE ECKDATEN</span><h2>Vor der Buchung vollständig transparent.</h2></div><div><dl><div><dt>Registrierung und Profilanlage</dt><dd>Kostenlos und ohne unmittelbare Zahlungspflicht</dd></div><div><dt>Freischaltung zur Zahlung</dt><dd>Erst nach abgeschlossener Prüfung der Anwaltszulassung</dd></div><div><dt>Preis</dt><dd>490 € netto monatlich bei zwölf Monaten Vertragslaufzeit</dd></div><div><dt>Zahlungsweise</dt><dd>5.880 € netto zuzüglich Umsatzsteuer für das Vertragsjahr im Voraus über Stripe</dd></div><div><dt>Erste Vertragslaufzeit</dt><dd>Zwölf Monate ab bestätigter Zahlung</dd></div><div><dt>Verlängerung</dt><dd>Automatisch um jeweils weitere zwölf Monate</dd></div><div><dt>Kündigungsfrist</dt><dd>Spätestens drei Monate vor Ende der jeweiligen Laufzeit im Portal</dd></div><div><dt>Mandatsvergütung</dt><dd>Nicht Bestandteil des Portalvertrags; Vereinbarung ausschließlich zwischen Kanzlei und Mandant</dd></div></dl><small>Die vollständigen Vertragsbedingungen und die konkrete Leistungsbeschreibung werden vor der kostenpflichtigen Buchung angezeigt und müssen ausdrücklich bestätigt werden.</small></div></section>

    <section className="section-wrap faq lawyer-faq"><div><span className="section-label">HÄUFIGE FRAGEN</span><h2>Was Kanzleien vorab wissen möchten.</h2></div><div className="faq-list">
      <details><summary>Kann ich mein Profil anlegen, ohne sofort zu bezahlen?<span>+</span></summary><p>Ja. Registrierung, Profilanlage, Auswahl der Tätigkeitsgebiete und Profilvorschau erfolgen vor der Zahlung. Erst nach der Zulassungsprüfung entscheiden Sie, ob Sie den Jahreszugang über Stripe buchen.</p></details>
      <details><summary>Erhalte ich garantierte Mandate?<span>+</span></summary><p>Nein. Garantiert ist ausschließlich das ausgewiesene Mediabudget. Zahl, Qualität und Ausgang möglicher Kontakte hängen unter anderem von Nachfrage, Rechtsgebiet, Region, Profil, Nutzerauswahl und Ihrer Verfügbarkeit ab.</p></details>
      <details><summary>Kann ein Nutzer mein Profil öffentlich finden?<span>+</span></summary><p>Nein. Anwaltsprofile werden nicht öffentlich gelistet. Sie erscheinen nur angemeldeten Nutzern nach einem bezahlten Rechtsfall-Check und nur bei erfüllten Matching-Kriterien.</p></details>
      <details><summary>Wann sehe ich Kontaktdaten und Prüfbericht?<span>+</span></summary><p>Erst wenn der Nutzer Ihr Profil aktiv auswählt und die Übermittlung ausdrücklich bestätigt. Vorher sehen Sie weder den Nutzer noch dessen Sachverhalt.</p></details>
      <details><summary>Entsteht durch die Chatnachricht bereits ein Mandat?<span>+</span></summary><p>Nein. Der Chat dient der Kontaktanbahnung. Sie prüfen insbesondere Identität, mögliche Interessenkollisionen, Kapazität, Fristen und Mandatsbedingungen eigenverantwortlich.</p></details>
      <details><summary>Kann ich zeitweise keine neuen Anfragen annehmen?<span>+</span></summary><p>Die Mandatsbereitschaft ist ein Matching-Kriterium. Bei deaktivierter Bereitschaft wird Ihr Profil nicht für neue Kontakte berücksichtigt.</p></details>
      <details><summary>Wie kündige ich?<span>+</span></summary><p>Die Kündigung wird im Anwaltsportal erklärt und ausgelöst. Sie muss spätestens drei Monate vor Ende der laufenden Vertragsperiode eingehen; andernfalls verlängert sich der Vertrag um zwölf Monate.</p></details>
    </div></section>

    <section className="lawyer-public-cta"><div><span className="section-label light-label">UNVERBINDLICH STARTEN</span><h2>Erstellen Sie zuerst in Ruhe Ihr Kanzleiprofil.</h2><p>Sie sehen den Ablauf, vervollständigen alle Angaben und prüfen Ihre Profilvorschau. Eine Zahlung wird erst nach bestätigter Zulassung und Ihrer ausdrücklichen Buchung ausgelöst.</p><Link className="button button-light" href={signup}>Zur kostenlosen Kanzlei-Registrierung →</Link><Link href="/anmelden?returnTo=%2Fanwalt">Bereits registriert? Zum Anwaltszugang</Link></div></section>
  </main><SiteFooter/></div>;
}

