import { integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

const timestamps={createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)};
export const users=sqliteTable("users",{id:text("id").primaryKey(),email:text("email").notNull(),displayName:text("display_name"),...timestamps},t=>[uniqueIndex("users_email_uq").on(t.email)]);
export const cases=sqliteTable("cases",{id:text("id").primaryKey(),ownerId:text("owner_id").notNull().references(()=>users.id),legalArea:text("legal_area").notNull().default("consumer_purchase_dummy"),status:text("status").notNull().default("DRAFT"),title:text("title").notNull(),retentionUntil:text("retention_until"),...timestamps});
export const documents=sqliteTable("documents",{id:text("id").primaryKey(),caseId:text("case_id").notNull().references(()=>cases.id),objectKey:text("object_key").notNull(),originalName:text("original_name").notNull(),mimeType:text("mime_type").notNull(),sizeBytes:integer("size_bytes").notNull(),sha256:text("sha256").notNull(),scanStatus:text("scan_status").notNull().default("PENDING"),extractionStatus:text("extraction_status").notNull().default("PENDING"),...timestamps});
export const facts=sqliteTable("facts",{id:text("id").primaryKey(),caseId:text("case_id").notNull().references(()=>cases.id),predicate:text("predicate").notNull(),value:text("value").notNull(),status:text("status").notNull().default("UNVERIFIED"),confidence:integer("confidence").notNull().default(0),...timestamps});
export const evidenceLinks=sqliteTable("evidence_links",{id:text("id").primaryKey(),factId:text("fact_id").notNull().references(()=>facts.id),documentId:text("document_id").notNull().references(()=>documents.id),page:integer("page"),quote:text("quote"),...timestamps});
export const questions=sqliteTable("questions",{id:text("id").primaryKey(),caseId:text("case_id").notNull().references(()=>cases.id),questionKey:text("question_key").notNull(),prompt:text("prompt").notNull(),answer:text("answer"),status:text("status").notNull().default("OPEN"),...timestamps});
export const assessments=sqliteTable("assessments",{id:text("id").primaryKey(),caseId:text("case_id").notNull().references(()=>cases.id),version:integer("version").notNull(),decision:text("decision").notNull(),payloadJson:text("payload_json").notNull(),legalContentVersion:text("legal_content_version").notNull(),...timestamps});
export const auditEvents=sqliteTable("audit_events",{id:text("id").primaryKey(),caseId:text("case_id"),actorId:text("actor_id"),eventType:text("event_type").notNull(),targetType:text("target_type"),targetId:text("target_id"),metadataJson:text("metadata_json").notNull().default("{}"),ipHash:text("ip_hash"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
