import type {Metadata} from "next";
import {SiteFooter,SiteHeader} from "@/app/components/site-chrome";
import "../legal-pages.css";

export const metadata:Metadata={title:"Datenschutzerklärung",description:"Datenschutzinformationen für Rechtsfall-Check.de, Nutzerkonten, Fallakten, Dokumente und KI-Verarbeitung.",alternates:{canonical:"/datenschutz"}};
const toc=[["verantwortlicher","Verantwortlicher"],["ueberblick","Überblick"],["fallakten","Fallakten & Uploads"],["ki","KI-Verarbeitung"],["konto","Konto & Sicherheit"],["zahlung","Zahlung"],["dienstleister","Dienstleister"],["drittland","Drittländer"],["speicherung","Speicherung & Löschung"],["rechte","Ihre Rechte"],["cookies","Cookies"],["automatisierung","Automatisierung"],["sicherheit","Sicherheit"],["aenderungen","Änderungen"]];

export default function PrivacyPage(){return <div className="site"><SiteHeader/><main>
  <header className="legal-hero"><span className="section-label">DATENSCHUTZ</span><h1>Ihre Fallakte verdient besonderen Schutz.</h1><p>Diese Erklärung erläutert transparent, welche Daten Rechtsfall-Check.de verarbeitet – insbesondere bei Fallschilderungen, Dokumentenuploads und der KI-gestützten Vorprüfung.</p></header>
  <div className="legal-shell"><nav className="legal-toc" aria-label="Inhalt"><strong>INHALT</strong>{toc.map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav>
  <article className="legal-content"><span className="legal-version">Stand: 27. Juli 2026</span>
    <p>Rechtsfälle können hochsensible Informationen über Sie und andere Personen enthalten. Wir beschränken die Verarbeitung auf den jeweiligen Zweck, trennen Nutzerkonten und Fallakten und geben Inhalte nicht für Werbung oder den allgemeinen KI-Modellaufbau frei.</p>
    <section id="verantwortlicher"><h2>1. Verantwortlicher</h2><div className="legal-contact"><p><strong>Media Online Innovations Group</strong></p><p>Inhaber: Martin Kelm</p><p>Im Weidenblech 25, 51371 Leverkusen</p><p>Telefon: <a href="tel:+4921433014060">0214 / 330 140 60</a></p><p>E-Mail: <a href="mailto:mail@media-online-innovations.group">mail@media-online-innovations.group</a></p></div><p>Über diese Kontaktdaten können Sie Datenschutzanfragen stellen. Bitte senden Sie keine Fallunterlagen unverschlüsselt per E-Mail. Ein Datenschutzbeauftragter ist derzeit nicht benannt. Sollte eine gesetzliche Benennungspflicht entstehen, werden die Angaben hier ergänzt.</p></section>
    <section id="ueberblick"><h2>2. Kategorien, Zwecke und Rechtsgrundlagen</h2><table className="legal-table"><thead><tr><th>Daten</th><th>Zweck</th><th>Rechtsgrundlage</th></tr></thead><tbody>
      <tr><td>IP-Adresse, Zeitpunkt, Browser-, Geräte- und Serverdaten</td><td>Auslieferung, Stabilität, Missbrauchs- und Angriffserkennung</td><td>Art. 6 Abs. 1 lit. f DSGVO; berechtigtes Interesse am sicheren Betrieb</td></tr>
      <tr><td>Name, E-Mail-Adresse, Passwort-Hash, Sitzungsdaten</td><td>Registrierung, Login, Kontoverwaltung und Kommunikation</td><td>Art. 6 Abs. 1 lit. b DSGVO</td></tr>
      <tr><td>Fallbeschreibung, Ereignisdaten, Rechtsgebiet, Rückfragen und Ergebnisse</td><td>Vertragliche Fallaufnahme und Rechtsfall Check</td><td>Art. 6 Abs. 1 lit. b DSGVO; bei besonderen Daten zusätzlich Art. 9 Abs. 2 DSGVO</td></tr>
      <tr><td>Hochgeladene Dokumente, Bilder, Metadaten und Extrakte</td><td>Dokumentenprüfung, Belegzuordnung, Sicherheitsprüfung</td><td>Art. 6 Abs. 1 lit. b DSGVO; gegebenenfalls Art. 6 Abs. 1 lit. f und Art. 9 Abs. 2 lit. f DSGVO</td></tr>
      <tr><td>Zahlungsstatus, Betrag, Transaktions- und Rechnungsdaten</td><td>Zahlungsabwicklung, Buchhaltung, Betrugsprävention</td><td>Art. 6 Abs. 1 lit. b, c und f DSGVO</td></tr>
      <tr><td>Audit- und Sicherheitsereignisse</td><td>Zugriffsnachweis, Fehleranalyse, Abwehr und Compliance</td><td>Art. 6 Abs. 1 lit. f DSGVO</td></tr>
      <tr><td>Einwilligungsnachweise</td><td>Nachweis erteilter oder widerrufener Einwilligungen</td><td>Art. 6 Abs. 1 lit. c, Art. 7 Abs. 1 DSGVO</td></tr>
    </tbody></table><p>Soweit eine Verarbeitung für die Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist, können Art. 6 Abs. 1 lit. f DSGVO und bei besonderen Kategorien Art. 9 Abs. 2 lit. f DSGVO einschlägig sein. Wo eine ausdrückliche Einwilligung erforderlich ist, stützen wir die Verarbeitung auf Art. 6 Abs. 1 lit. a beziehungsweise Art. 9 Abs. 2 lit. a DSGVO. Eine Einwilligung ist freiwillig und jederzeit mit Wirkung für die Zukunft widerrufbar; ohne erforderliche Daten kann der Rechtsfall Check gegebenenfalls nicht erbracht werden.</p></section>
    <section id="fallakten"><h2>3. Fallakten und hochgeladene Dokumente</h2><p>Sie können Sachverhalte schildern und PDF-, JPG- oder PNG-Dateien hochladen. Dabei können Vertragsdaten, Kommunikation, Adressen, Kennzeichen, finanzielle Verhältnisse, Gesundheitsangaben, familiäre Informationen, Gewerkschaftszugehörigkeit, Daten zu Sexualleben oder sexueller Orientierung sowie Angaben über Vorwürfe, Straftaten oder Verfahren enthalten sein.</p><h3>Daten anderer Personen</h3><p>Unterlagen können Daten von Vertragspartnern, Angehörigen, Beschäftigten, Zeugen, Gegnern oder weiteren Beteiligten enthalten. Laden Sie nur Informationen hoch, die für Ihren Fall erforderlich sind und deren Verarbeitung zulässig ist. Schwärzen Sie insbesondere unnötige Kontaktdaten, Ausweisnummern, Gesundheitsangaben und Daten unbeteiligter Personen.</p><p>Soweit Daten nicht direkt bei der betroffenen Person erhoben werden, stammen sie aus den Angaben und Unterlagen des Nutzers. Eine individuelle Information jeder darin genannten Person kann unter den Voraussetzungen des Art. 14 Abs. 5 DSGVO entfallen, insbesondere wenn sie unmöglich wäre, unverhältnismäßigen Aufwand erfordern oder die Geltendmachung von Rechtsansprüchen beeinträchtigen würde. Die Rechte betroffener Personen bleiben bestehen.</p><h3>Sicherheits- und Extraktionspipeline</h3><p>Dateien werden einem Nutzer und einer Fallakte zugeordnet, anhand von Dateityp und Dateisignatur geprüft, gehasht und in einem privaten Objektspeicher abgelegt. Bis zur Freigabe durch vorgesehene Sicherheitsprüfungen können Dateien in Quarantäne verbleiben. Nach der ausdrücklichen KI-Einwilligung erkennt die Dokumentenpipeline auch eingescannte Inhalte und Bilder, führt erforderlichenfalls eine Texterkennung aus und speichert strukturierte, seitenbezogene Feststellungen sowie Qualitäts- und Warnhinweise. Es wird keine zusätzliche vollständige Textkopie des Dokuments gespeichert.</p><div className="legal-note">Übermitteln Sie keine Originaldateien, deren einziger Verlust Ihre Rechtsposition gefährden würde. Bewahren Sie stets eine eigene Kopie auf.</div></section>
    <section id="ki"><h2>4. KI-gestützte Verarbeitung</h2><p>Nach Ihrer ausdrücklichen Aktivierung können Fallangaben an einen konfigurierten KI-Dienstleister übermittelt werden, derzeit technisch vorgesehen: OpenAI. Die Verarbeitung dient der Strukturierung des Sachverhalts, Erkennung offener Punkte, Bildung von Rückfragen und Erstellung einer nicht abschließenden Ersteinschätzung.</p><ul><li>Die API-Anfrage wird mit deaktivierter anwendungsseitiger Speicherung des Modellergebnisses beim Anbieter konfiguriert, soweit die Schnittstelle dies unterstützt.</li><li>Fallinhalte werden nicht von uns für Werbung oder das Training eigener allgemeiner KI-Modelle verwendet.</li><li>Vor der Fallbewertung werden direkte Identifikatoren wie E-Mail-Adressen, Telefonnummern, IBANs, Anschriften und typische Kunden-, Vertrags-, Buchungs- oder Aktennummern automatisiert durch neutrale Platzhalter ersetzt. Rollen, Beträge, Termine und rechtlich relevante Abläufe bleiben erhalten.</li><li>Zur Auslesung einer hochgeladenen Originalunterlage muss deren Inhalt verarbeitet werden. Dabei wird ein neutraler Dateiname verwendet und das Analysesystem angewiesen, direkte Identifikatoren nicht in das strukturierte Extraktionsergebnis zu übernehmen.</li><li>Es werden möglichst nur die für den jeweiligen Analyseschritt erforderlichen Inhalte übermittelt.</li><li>Ein pseudonymer Sicherheitsbezeichner kann zur Missbrauchsprävention eingesetzt werden.</li><li>KI-Ausgaben können fehlerhaft sein und werden durch technische Qualitätsgates begrenzt; sie sind keine verbindliche Rechtsentscheidung.</li></ul><p>Enthält ein Fall besondere Kategorien personenbezogener Daten, wird vor der KI-Verarbeitung eine gesonderte ausdrückliche Einwilligung beziehungsweise eine andere tragfähige Rechtsgrundlage benötigt. Die Verarbeitung von Daten über strafrechtliche Verurteilungen und Straftaten unterliegt Art. 10 DSGVO und kann bis zur rechtlichen Freigabe eingeschränkt oder abgelehnt werden.</p><p>Die abschließende Auswahl von KI-, OCR- oder Analyseanbietern erfolgt erst nach Datenschutz-, Sicherheits- und Vertragsprüfung. Anbieterwechsel werden in dieser Erklärung dokumentiert.</p></section>
    <section id="konto"><h2>5. Nutzerkonto, Login und Kommunikation</h2><p>Zur Kontoführung verarbeiten wir Name, E-Mail-Adresse, Passwort-Hash, Sitzungskennungen und Sicherheitsinformationen. Passwörter werden nicht im Klartext gespeichert. Registrierung und Login erfolgen ausschließlich mit E-Mail-Adresse und Passwort. Die E-Mail-Adresse wird vor Freischaltung des Nutzerkontos bestätigt.</p><p>Notwendige transaktionale Nachrichten, etwa zur E-Mail-Bestätigung, Passwortwiederherstellung, Konto-, Zahlungs- oder Sicherheitsverwaltung, werden auf Grundlage der Vertragsdurchführung beziehungsweise unseres Sicherheitsinteresses über SendGrid versandt. Werbliche E-Mails erfolgen nur bei eigener Rechtsgrundlage.</p></section>
    <section id="zahlung"><h2>6. Zahlung über Stripe</h2><p>Für den Preis von 19 Euro je eingereichtem Rechtsfall Check wird Stripe als Zahlungsdienstleister eingesetzt. Stripe verarbeitet unter anderem Zahlungsart, Betrag, Währung, Transaktionskennung, technische Daten und – abhängig von der Zahlungsart – Rechnungs- und Zahlungsdaten. Vollständige Karteninformationen werden grundsätzlich unmittelbar durch Stripe verarbeitet und nicht in unserer Anwendungsdatenbank gespeichert.</p><p>Wir erhalten insbesondere Zahlungsstatus, Transaktionsreferenz und abrechnungsrelevante Angaben. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO sowie gesetzliche Aufbewahrungspflichten nach Art. 6 Abs. 1 lit. c DSGVO.</p></section>
    <section id="dienstleister"><h2>7. Hosting und Auftragsverarbeiter</h2><table className="legal-table"><thead><tr><th>Empfänger</th><th>Aufgabe</th><th>Betroffene Daten</th></tr></thead><tbody>
      <tr><td>Vercel</td><td>Hosting, Auslieferung, Serverfunktionen und privater Blob-Speicher</td><td>Verbindungsdaten, Anwendungsdaten, verschlüsselt übertragene Fall- und Dokumentdaten</td></tr>
      <tr><td>Railway</td><td>PostgreSQL-Datenbank</td><td>Konto-, Fall-, Metadaten, Ergebnisse, Audit- und Zahlungsstatus</td></tr>
      <tr><td>OpenAI, sofern aktiviert</td><td>KI-gestützte Dokument- und Texterkennung, Strukturierung und Fallanalyse</td><td>Für die Analyse ausgewählte Fallangaben und hochgeladene Unterlagen; keine Zahlungsdaten</td></tr>
      <tr><td>Stripe</td><td>Checkout, Zahlung, Betrugsprävention</td><td>Transaktions-, Zahlungs-, Kontakt- und technische Daten</td></tr>
      <tr><td>Twilio SendGrid</td><td>Transaktionaler E-Mail-Versand</td><td>Name, E-Mail-Adresse, Nachrichtentyp und technische Zustelldaten; keine Fallinhalte oder Dokumente</td></tr>
      <tr><td>Railway / ClamAV</td><td>Schadsoftware- und Virenprüfung vor Speicherung</td><td>Dateiinhalt und technische Prüfdaten; keine dauerhafte Ablage im Scanner</td></tr>
    </tbody></table><p>Dienstleister werden nur im erforderlichen Umfang eingebunden. Soweit sie Auftragsverarbeiter sind, werden Verträge nach Art. 28 DSGVO geschlossen. Manche Anbieter handeln für einzelne Verarbeitungsschritte eigenverantwortlich, insbesondere Zahlungsdienstleister.</p></section>
    <section id="drittland"><h2>8. Übermittlungen in Drittländer</h2><p>Bei US-amerikanischen oder global betriebenen Dienstleistern kann eine Verarbeitung außerhalb des Europäischen Wirtschaftsraums nicht ausgeschlossen werden. Eine Übermittlung erfolgt nur, wenn die Voraussetzungen der Art. 44 ff. DSGVO erfüllt sind, insbesondere aufgrund eines Angemessenheitsbeschlusses – gegebenenfalls des EU-US Data Privacy Framework – oder von EU-Standardvertragsklauseln und ergänzenden Schutzmaßnahmen.</p><p>Welche Garantie konkret gilt, hängt vom ausgewählten Anbieter, dessen Zertifizierung und der vereinbarten Region ab. Eine Kopie oder Information zu den eingesetzten Garantien können Sie über die oben genannten Kontaktdaten anfordern.</p></section>
    <section id="speicherung"><h2>9. Aufbewahrung und Löschung</h2><p>Wir speichern Daten nur so lange, wie dies für den jeweiligen Zweck erforderlich ist oder gesetzliche Pflichten und die Verteidigung von Ansprüchen dies verlangen.</p><table className="legal-table"><thead><tr><th>Datenart</th><th>Regelfrist beziehungsweise Kriterium</th></tr></thead><tbody>
      <tr><td>Unbezahlte Fallentwürfe und hochgeladene Dokumente</td><td>Grundsätzlich 30 Tage ab Anlage beziehungsweise letzter aktiver Bearbeitung, sofern keine frühere Löschung verlangt wird und keine Sicherungsgründe entgegenstehen.</td></tr>
      <tr><td>Bezahlte Fallakten und Ergebnisse</td><td>Während der Bereitstellung im Nutzerkonto; anschließend Löschung auf Anfrage oder nach Wegfall des Vertragszwecks, soweit keine Nachweis- oder Verjährungsfristen entgegenstehen.</td></tr>
      <tr><td>Konto</td><td>Bis zur Kontolöschung. Nutzer können eine Löschung mit 30-tägiger Widerrufsfrist vormerken oder nach ausdrücklicher Bestätigung die sofortige Löschung wählen.</td></tr>
      <tr><td>Zahlungs- und Buchungsbelege</td><td>Nach den handels- und steuerrechtlichen Aufbewahrungsfristen, regelmäßig bis zu acht beziehungsweise zehn Jahre abhängig von der Belegart und Rechtslage.</td></tr>
      <tr><td>Sicherheits- und Auditdaten</td><td>So kurz wie möglich, abhängig von Sicherheits-, Nachweis- und Verjährungsbedarf.</td></tr>
      <tr><td>Backups und Providerkopien</td><td>Löschung im regulären Überschreibungszyklus; bis dahin gesperrt und nur zur Wiederherstellung verwendet.</td></tr>
    </tbody></table><p>Bei der endgültigen Kontolöschung werden in unserer aktiven Anwendungsumgebung das Nutzerkonto, Zugangsdaten und Sitzungen, Profilinformationen, sämtliche Fallaufnahmen, Antworten, Dokumente im privaten Objektspeicher, Extrakte, KI-Ausgaben, Prüfberichte, Fallprotokolle und lokale Zahlungsverknüpfungen entfernt. Bei der vorgemerkten Löschung bleibt das Konto während der 30-tägigen Widerrufsfrist aktiv; anschließend verarbeitet ein täglicher Löschjob den Auftrag. Bei der Option „sofort löschen“ verzichtet der Nutzer nach gesonderter Bestätigung auf diese Frist.</p><p>Technische Sicherungskopien werden nicht erneut in den Produktivbetrieb übernommen und im regulären, zugriffsbeschränkten Überschreibungszyklus des jeweiligen Infrastrukturbetreibers entfernt. Eigenständige Aufzeichnungen von Zahlungsdienstleistern, insbesondere Stripe, können wegen gesetzlicher Aufbewahrungs-, Geldwäsche-, Betrugspräventions- oder Nachweispflichten außerhalb unserer aktiven Anwendungsdatenbank fortbestehen. Hierfür gelten die Informationen und Betroffenenrechte des jeweiligen Zahlungsdienstleisters.</p></section>
    <section id="rechte"><h2>10. Ihre Datenschutzrechte</h2><p>Sie haben nach Maßgabe der DSGVO insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch gegen Verarbeitungen auf Grundlage berechtigter Interessen. Erteilte Einwilligungen können jederzeit mit Wirkung für die Zukunft widerrufen werden.</p><p>Zur Vermeidung einer unbefugten Offenlegung können wir einen Identitätsnachweis verlangen. Sie haben außerdem das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren. Für einen in Nordrhein-Westfalen niedergelassenen privaten Verantwortlichen ist grundsätzlich die Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen, Kavalleriestraße 2–4, 40213 Düsseldorf, <a href="https://www.ldi.nrw.de">www.ldi.nrw.de</a>, zuständig.</p><p>Ein Widerspruch gegen Direktwerbung wirkt ohne Interessenabwägung. Direktwerbung ist derzeit nicht Bestandteil des Rechtsfall Checks.</p></section>
    <section id="cookies"><h2>11. Cookies, lokale Speicherung und Web-App</h2><p>Wir verwenden technisch erforderliche Cookies und vergleichbare Speichermechanismen für Login, Sitzungssicherheit, CSRF-Schutz, Sprache, Installationsstatus und ausdrücklich gewünschte Funktionen. Rechtsgrundlage ist § 25 Abs. 2 Nr. 2 TDDDG in Verbindung mit Art. 6 Abs. 1 lit. b oder f DSGVO.</p><p>Nicht erforderliche Analyse-, Marketing- oder Profiling-Technologien werden derzeit nicht eingesetzt. Sollten solche Dienste hinzukommen, werden sie erst nach vorheriger Einwilligung aktiviert und in dieser Erklärung sowie den Einwilligungseinstellungen beschrieben.</p></section>
    <section id="automatisierung"><h2>12. Automatisierte Verarbeitung und Art. 22 DSGVO</h2><p>Der Rechtsfall Check verwendet automatisierte Verfahren zur Strukturierung und vorläufigen Einordnung. Das Ergebnis entfaltet keine Rechtswirkung und beeinträchtigt Sie nicht in ähnlich erheblicher Weise. Es entscheidet nicht über Ansprüche, den Zugang zu Gerichten, Versicherungsleistungen, Kredit, Beschäftigung oder behördliche Maßnahmen.</p><p>Bei unzureichender Datenlage, unsicheren Fristen, hoher Tragweite oder nicht freigegebenen Quellen soll das System eine Nicht-Antwort beziehungsweise Eskalation ausgeben. Eine verbindliche Einzelfallentscheidung bleibt hierzu befugten Menschen und Stellen vorbehalten.</p></section>
    <section id="sicherheit"><h2>13. Technische und organisatorische Maßnahmen</h2><p>Vorgesehen sind insbesondere TLS-verschlüsselte Übertragung, kontogebundene Zugriffskontrolle, serverseitige Eigentümerprüfung, private Dokumentablage, Quarantäne, Dateisignatur- und Hashprüfung, automatische Malware- und Virenprüfung vor der dauerhaften Speicherung, rollen- und zweckgebundene Zugriffe, Protokollierung sicherheitsrelevanter Ereignisse, Geheimnisverwaltung und getrennte Produktionsumgebungen.</p><p>Trotz angemessener Maßnahmen kann keine Datenübertragung oder Speicherung absolut risikofrei sein. Bei einer Verletzung des Schutzes personenbezogener Daten erfüllen wir die gesetzlichen Prüf-, Dokumentations- und Meldepflichten nach Art. 33 und 34 DSGVO.</p><p>Vor Verarbeitung realer sensibler Fallakten ist eine Datenschutz-Folgenabschätzung nach Art. 35 DSGVO vorgesehen. Weitere OCR- oder juristische Wissensanbieter werden erst nach Datenschutz-, Sicherheits- und Vertragsprüfung aktiviert.</p></section>
    <section id="support"><h2>14. Support-Tickets und Nachrichten</h2><p>Wenn Sie das Support-Center nutzen, verarbeiten wir Ticketnummer, Thema, Betreff, Nachrichten, Zeitpunkte, Bearbeitungsstatus sowie optional die Zuordnung zu einer eigenen Fallakte. Die Verarbeitung dient der Bearbeitung technischer, organisatorischer und vertraglicher Anliegen auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO sowie unserer berechtigten Interessen an einem sicheren und nachvollziehbaren Support nach Art. 6 Abs. 1 lit. f DSGVO.</p><p>Support-Tickets dienen nicht der rechtlichen Beratung oder erneuten inhaltlichen Bewertung eines Rechtsfall-Checks. Bitte übermitteln Sie deshalb keine zusätzlichen sensiblen Fallinhalte. Support-Nachrichten werden kontogebunden gespeichert, in den persönlichen Datenexport einbezogen und bei endgültiger Kontolöschung aus der aktiven Anwendungsumgebung entfernt, soweit keine gesetzlichen Aufbewahrungs- oder Nachweispflichten entgegenstehen.</p></section>
    <section id="aenderungen"><h2>15. Änderungen dieser Datenschutzerklärung</h2><p>Wir aktualisieren diese Erklärung bei Änderungen der Verarbeitung, Dienstleister oder Rechtslage. Die jeweils aktuelle Fassung ist unter dieser Adresse abrufbar. Bei wesentlichen Änderungen, die ein bestehendes Nutzerkonto betreffen, informieren wir in geeigneter Weise.</p></section>
  </article></div><SiteFooter/></main></div>}
