"use client";

import { FormEvent, useState } from "react";
import { authClient } from "@/lib/auth-client";

type Notice = { type: "success" | "error"; text: string } | null;

export function TwoFactorSettings({ initialEnabled }: { initialEnabled: boolean }) {
  const [enabled,setEnabled]=useState(initialEnabled); const [password,setPassword]=useState("");
  const [code,setCode]=useState(""); const [totpUri,setTotpUri]=useState("");
  const [backupCodes,setBackupCodes]=useState<string[]>([]); const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState<Notice>(null);
  async function begin(event:FormEvent){event.preventDefault();setBusy(true);setNotice(null);const {data,error}=await authClient.twoFactor.enable({password,issuer:"Rechtsfall-Check.de"});setBusy(false);if(error||!data){setNotice({type:"error",text:error?.message||"2FA konnte nicht vorbereitet werden. Prüfen Sie Ihr Passwort."});return}setTotpUri(data.totpURI);setBackupCodes(data.backupCodes);setPassword("");setNotice({type:"success",text:"Fügen Sie den Schlüssel Ihrer Authenticator-App hinzu und bestätigen Sie die Einrichtung mit einem aktuellen Code."})}
  async function confirm(event:FormEvent){event.preventDefault();setBusy(true);setNotice(null);const {error}=await authClient.twoFactor.verifyTotp({code:code.replace(/\s/g,""),trustDevice:true});setBusy(false);if(error){setNotice({type:"error",text:error.message||"Der Code ist ungültig oder abgelaufen."});return}setEnabled(true);setTotpUri("");setCode("");setNotice({type:"success",text:"Zwei-Faktor-Authentifizierung ist jetzt aktiv. Bewahren Sie Ihre Wiederherstellungscodes sicher auf."})}
  async function disable(event:FormEvent){event.preventDefault();setBusy(true);setNotice(null);const {error}=await authClient.twoFactor.disable({password});setBusy(false);if(error){setNotice({type:"error",text:error.message||"2FA konnte nicht deaktiviert werden."});return}setEnabled(false);setPassword("");setBackupCodes([]);setNotice({type:"success",text:"Zwei-Faktor-Authentifizierung wurde deaktiviert."})}
  async function renew(){setBusy(true);setNotice(null);const {data,error}=await authClient.twoFactor.generateBackupCodes({password});setBusy(false);if(error||!data){setNotice({type:"error",text:error?.message||"Neue Wiederherstellungscodes konnten nicht erstellt werden."});return}setBackupCodes(data.backupCodes);setPassword("");setNotice({type:"success",text:"Neue Wiederherstellungscodes wurden erstellt. Vorherige Codes sind ungültig."})}
  function download(){const blob=new Blob([`Rechtsfall-Check.de Wiederherstellungscodes\n\n${backupCodes.join("\n")}\n`],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="rechtsfall-check-wiederherstellungscodes.txt";link.click();URL.revokeObjectURL(url)}
  const secret=totpUri?new URL(totpUri).searchParams.get("secret"):"";
  return <div className="app-card profile-card two-factor-card">
    <div className="profile-card-head"><div className="profile-card-icon" aria-hidden="true">04</div><div><h2>Zwei-Faktor-Authentifizierung</h2><p>Schützen Sie Ihr Konto mit einem zeitbasierten Code aus Ihrer Authenticator-App.</p></div><span className={`two-factor-status ${enabled?"active":""}`}>{enabled?"Aktiv":"Nicht aktiv"}</span></div>
    {notice&&<div className={`profile-notice ${notice.type}`} role={notice.type==="error"?"alert":"status"}>{notice.text}</div>}
    {!enabled&&!totpUri&&<form className="two-factor-form" onSubmit={begin}><div className="field"><label htmlFor="twoFactorPassword">Aktuelles Passwort bestätigen</label><input id="twoFactorPassword" type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required/></div><button className="button" disabled={busy}>{busy?"Wird vorbereitet …":"2FA einrichten"}</button></form>}
    {!enabled&&totpUri&&<form className="two-factor-enrollment" onSubmit={confirm}><div className="two-factor-steps"><strong>1. Authenticator-App öffnen</strong><p>Fügen Sie ein neues Konto hinzu. Auf dem Smartphone können Sie den Link direkt öffnen oder den Schlüssel manuell eintragen.</p><a className="button secondary" href={totpUri}>In Authenticator-App öffnen</a><code>{secret}</code><small>Typ: zeitbasiert (TOTP) · 6 Stellen · 30 Sekunden</small></div><div className="field"><label htmlFor="twoFactorCode">2. Aktuellen sechsstelligen Code</label><input id="twoFactorCode" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,""))} required placeholder="123456"/></div><button className="button" disabled={busy||code.length!==6}>{busy?"Code wird geprüft …":"2FA verbindlich aktivieren"}</button></form>}
    {enabled&&<form className="two-factor-form" onSubmit={disable}><div className="field"><label htmlFor="twoFactorManagePassword">Aktuelles Passwort</label><input id="twoFactorManagePassword" type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required/></div><div className="two-factor-actions"><button className="button secondary" type="button" disabled={busy||!password} onClick={renew}>Neue Wiederherstellungscodes</button><button className="button danger-button" disabled={busy}>2FA deaktivieren</button></div></form>}
    {backupCodes.length>0&&<div className="backup-codes" role="region" aria-label="Wiederherstellungscodes"><strong>Wiederherstellungscodes – nur einmal sicher speichern</strong><p>Jeder Code kann einmal verwendet werden. Geben Sie diese Codes niemals weiter.</p><div>{backupCodes.map(item=><code key={item}>{item}</code>)}</div><button className="button secondary" type="button" onClick={download}>Codes herunterladen</button></div>}
  </div>;
}
